### ISSUE TITLE
bug launch

### ISSUE THREAD

**Issue by ghost** [lukasmonk/lucaschessR2#1]
Unable to launch lucas chess under linux, error message.
I am under manjaro gnome
![Capture d’écran du 2022-03-19 12-16-44](https://user-images.githubusercontent.com/77933011/159118955-5dfe8a2b-c354-450f-baa5-e67f11c04ad6.png)

**Comment by lukasmonk** [comment]
I have no idea what the problem might be,
Doing a google search, for example at [https://forum.garudalinux.org/t/no-such-key-antialiasing-error/11825](link) suggests:

Remove the lines containing antialising in usr/share/glib-2.0/schemas/25_gnome-default-settings.gschema.override and then, recompile schema, sudo glib-compile-schemas /usr/share/glib-2.0/schemas **_Beware! This might break your schema!_** **Make backup before performing this.**

**Comment by franissirkovic** [comment]
It seems to me that elo-estimation doesn't work properly during the analyze (at least it works differently than previous version).
I would guess that average elo is attached to a move (all previous moves). In effect, later moves have smaller effect in that case.
For example, move 12 with diff 1.11 gets elo 2992, and move 46 with diff 1.48 gets elo 3481.


Best wishes, Franis Sirkovic.

**Comment by lukasmonk** [comment]
This error appears when the server is Wayland. Switching to Xorg allows you to install the program (https://askubuntu.com/questions/1425165/lucaschess-wont-start-or-install-after-update-to-22-04-claiming-no-antialiasin). The alternative is to make a specific distribution as I have done with Ubuntu 22.04:  https://drive.google.com/file/d/1RpyDenar14faAjnrENa9gTQ7apD0qNHP/view?usp=sharing
