### ISSUE TITLE
BUG of dirve engine

### ISSUE THREAD

**Issue by shenjian333333** [lukasmonk/lucaschessR2#10]
The enginelog say ,lucas chess shut down the engine when engine was working,becaus that ,my depth can`t up to 30 . (sry for my bad english) XD
[Stockfish 15_00001.txt](https://github.com/lukasmonk/lucaschessR2/files/8546858/Stockfish.15_00001.txt)
.

**Comment by lukasmonk** [comment]
I need more information.
Which version are you using?
Which option within the programme are you running?

**Comment by shenjian333333** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 晚上9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lukasmonk/lucaschessR2] BUG of dirve engine (Issue #10)





 
I need more information.
 Which version are you using?
 Which option within the programme are you running?

**Comment by shenjian333333** [comment]
![bug](https://user-images.githubusercontent.com/93416267/164896443-bb85cf3f-4b2e-4de4-9269-824968f156d5.PNG)
![bug2](https://user-images.githubusercontent.com/93416267/164896452-e00c31f5-a0b1-4efa-a2b5-70c6c0f5ff5d.PNG)

**Comment by shenjian333333** [comment]
Here `s my option

**Comment by shenjian333333** [comment]
https://user-images.githubusercontent.com/93416267/164896524-e0a4c99c-723b-40fc-969e-f4d66f0caf7d.mp4

**Comment by shenjian333333** [comment]
And here `s the bug ,I was set 30 depth ,but it was stop on 28 and jump to 8 . I don`t know how to do

**Comment by lukasmonk** [comment]
![image](https://user-images.githubusercontent.com/6254278/164902304-52c6ddcd-6a79-40a1-82d1-0821d8babcbb.png)

**Comment by lukasmonk** [comment]
I need this screenshot (Analyzer tab) to know which options you are using.

**Comment by shenjian333333** [comment]
![Uploading BUG4.PNG…]()

**Comment by shenjian333333** [comment]
![BUG4](https://user-images.githubusercontent.com/93416267/164910044-3bed15ff-3e09-4208-80e1-e4e6970af553.PNG)

**Comment by shenjian333333** [comment]
sorry but I`m sleep now that`s 22:32 in beijing

**Comment by shenjian333333** [comment]
Hi , did you fix it ?

**Comment by lukasmonk** [comment]
I thought it was fixed. 
![image](https://user-images.githubusercontent.com/6254278/164976425-f858d748-730a-47e5-b95a-30c386e7a4da.png)

**Comment by shenjian333333** [comment]
wow ,let me try

**Comment by shenjian333333** [comment]
nice! I fixed it thank you  very much

**Comment by lukasmonk** [comment]
Good!

**Comment by shenjian333333** [comment]
This a very good opening source program! I was give you a start yesterday hope you like it!
