### ISSUE TITLE
Update Square Off Pro driver for Windows

### ISSUE THREAD

**Issue by JungleJ0n** [lukasmonk/lucaschessR2#103]
There has been an update to the Firmware for Square off pro board and this has seemingly broken the ability to connect using the current drivers (2.0).

Graham has updated the driver on his site (2.1)
https://goneill.co.nz/chess.php#squareoff

Can it also please be updated within Luca chess

**Comment by lukasmonk** [comment]
Graham states on his [website](https://goneill.co.nz/chess.php) that:
"WARNING! The Square Off Pro firmware update issued in June 2023 seems to have broken my driver (as well as some other apps). It might be possible for me to fix this but Square Off don't support third party developers so it might take some time."

**Comment by JungleJ0n** [comment]
I could be wrong but I don't believe that was on his site before I posted & contacted Graham directly and where he stated that.

btw many thanks for the work that you both have put in to your respective codes.

**Comment by JungleJ0n** [comment]
Luk you & Graham are gangsters.
