### ISSUE TITLE
Moves tree doesn't show white's first moves at initial position

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR2#11]
Hi,
If you paste a game in a database and go to initial position of the game (all pieces on their starting position) and open Moves tree, it doesn't show white's alternatives, instead it shows black's alternatives. So, if a user wants to add a comment on very first move of white, he has to open "Create your own game" and put the comment on white's first move. Unnecessary efforts!

**Comment by lukasmonk** [comment]
Fixed in the next update.
