### ISSUE TITLE
Can't connect SquareOff Pro Board anymore

### ISSUE THREAD

**Issue by tydan** [lukasmonk/lucaschessR2#115]
Hi Lucas !
I have a Square Off Pro board.
It was working before (don't know witch version of Lucas Chess it was), but with the latest version [R2.10a], I have "connection failed"

I use the lastest drivers from goneill.co.nz (SOP 2.2) and it works with Fritz 17 for example on my PC.

I noticed that the drivers included in LC R2.10a are SOP 2.0.
Maybe that's the problem ;)

Have a good day !

**Comment by lukasmonk** [comment]
Have you tried using the Information/Check for updates option?

**Comment by tydan** [comment]
You're right !
I thought my version was ok when I upgraded to R2.10a.
I did it once more thanks to your post and I have an updade to v17 concerning eBoard software.
Now it works.
Thank you, nice update process ;)
