### ISSUE TITLE
Extra space after the move and annotation prevents lichess parser from importing the whole game

### ISSUE THREAD

**Issue by SG7** [lukasmonk/lucaschessR2#12]
Example:
After exporting the Lucas game in PGN format (no comments) I got the following:

1.d4 b6 ?! 2.e4 Bb7 3.Nc3 d5 ?! 4.exd5 Bxd5 ?! 5.Nxd5 Qxd5 6.Nf3 Nf6 7.Bd3 ?! e6
8.O-O Bd6 9.Re1 O-O ?! 10.c4 ?! Qh5 11.h3 Nbd7 12.Bd2 ?! c5 13.Qc2 ?! cxd4 
14.Nxd4 Bc5 ?! 15.Nf3 ! Rad8 ?! 16.Bf1 ?! Rfe8 ? 17.Bf4 ?? e5 18.Bg3 e4 19.Nh2 ?
e3 ?! 20.Be2 ? exf2+ 21.Bxf2 Bxf2+ 22.Kxf2 Qc5+ 23.Kf1 Ne4 24.Qd3 ?? Qf2#

a)  ?!, ??,  ?, ! annotations are still present in the file - it would be nice to have an option to not have them.
b) Probably pgn format does not allow a space before annotation signs ?!
c) Lichess import parser stops after the first moves and shows:
1.d4 b6

**Comment by lukasmonk** [comment]
I believe it is a problem of LiChess parser.
I have removed the space anyway.
To the next R2.03
