### ISSUE TITLE
Opening Lines not Opening

### ISSUE THREAD

**Issue by Sellyax** [lukasmonk/lucaschessR2#122]
Hello,
When I go to Tools > Openings > Opening Lines nothing is opening.
It was/has worked but it is now not. After selecting Opening Lines, nothing pops up or opens but the window becomes deselected and trying to interact with Lucas Chess makes the windows error sound. 
If I hit escape then it lets me interact with Lucas Chess again.
Any ideas whats causing it? I've rebooted and reinstalled (i was originally on version 1.39 iirc and now on 2.10a and it's still happening).
Thanks,

**Comment by Sellyax** [comment]
Hello,
I was able to fix by deleting all folders that remained after uninstalling (in program data) and then reinstalling.

**Comment by lukasmonk** [comment]
Thanks for the information.
