### ISSUE TITLE
Installation script is unable to uninstall the installed version [Linux]

### ISSUE THREAD

**Issue by clozanoruiz** [lukasmonk/lucaschessR2#127]
Hi,
I just installed LucasChess R2 2.10a in Linux Mint 21.2 using the LINUX installation script. There were a few error messages during installation (they have been mentioned in other issues before) but the application seems to work except for the occasional crash when trying to import a PGN file - I think the error has been also discussed here and it was adviced to try the 'WALAND' version.

Before installing the WAYLAND version I run the LINUX installation script and, when clicking the 'Uninstall version installed' nothing happens as this error message appears in the console:
```
Traceback (most recent call last):
  File "setup_linux.py", line 269, in uninstall
AttributeError: module 'Code.QT.QTUtil2' has no attribute 'preguntaCancelar123'
```
I also run the WAYLAND version to see if I could uninstall from there but I get a similar error message in the console:
```
Traceback (most recent call last):
  File "setup_linux.py", line 269, in uninstall
NameError: name 'question_withcancel_123' is not defined
```

**Comment by lukasmonk** [comment]
Thanks. 
It will be fixed in the next update.
