### ISSUE TITLE
Error Run Application

### ISSUE THREAD

**Issue by maljos** [lukasmonk/lucaschessR2#128]
SO: MXLinux 23.1 Debian 12
Graphics Card: NVidia GTX 1660 Super
RAM: 16 GB

[22548] Failed to execute script 'Launcher' due to unhandled exception!
![2024-02-01_19-28](https://github.com/lukasmonk/lucaschessR2/assets/3738917/318a34da-6e0c-4105-8c60-47ba68b1a8de)

**Comment by lukasmonk** [comment]
I'm sorry but I couldn't replicate the error. On a virtual machine with Debian 12, I downloaded it and it launched without problems.
Is this the first installation?

**Comment by maljos** [comment]
Not, is the second

**Comment by lukasmonk** [comment]
Go to LucasChessR/bin/OS/linux and sh ./RunEngines and try again.

**Comment by maljos** [comment]
https://github.com/lukasmonk/lucaschessR2/assets/3738917/cd954d43-c40c-4786-a9fe-643af8affa2d

**Comment by lukasmonk** [comment]
That's after doing: Go to LucasChessR/bin/OS/linux and sh ./RunEngines and try again.

**Comment by maljos** [comment]
https://github.com/lukasmonk/lucaschessR2/assets/3738917/733df8eb-732d-4c79-a59d-128a34e2110a

**Comment by lukasmonk** [comment]
Sorry but not an easy task, because I can´t replicate the problem.
Have you tried installing the version again?

**Comment by maljos** [comment]
https://github.com/lukasmonk/lucaschessR2/assets/3738917/98301e4b-97e2-491f-b221-488b25b37068

**Comment by maljos** [comment]
Version 2.10a operative
![2024-02-02_15-07](https://github.com/lukasmonk/lucaschessR2/assets/3738917/909bcfc3-4643-445a-954c-b4c461394ba4)

**Comment by lukasmonk** [comment]
you can click on Information/Check for update.

**Comment by maljos** [comment]
It does not work. It gives the same error.

**Comment by lukasmonk** [comment]
Maybe the problem is that the new komodo versions are not compatible with your processor, a way to bypass the problem until I update the program is: 
Go to the /bin/OS/linux/Engines/komodo folder.
Delete the dragon-linux file
Rename komodo-14.1-linux to dragon-linux

**Comment by maljos** [comment]
It does not work. It gives the same error. no problem I will wait for your next update. Thank you for your attention

**Comment by lukasmonk** [comment]
I need you to help me. I can't possibly solve the problem if I don't know what the problem is.
Right now my only hypothesis is that some version of komodo doesn't work.

Could you tell me which version of komodo works on your computer.
I attach a link with the latest versions, I would need to know which of those works on your computer.
[https://www.filemail.com/d/qhtyczogbhalqqq](https://www.filemail.com/d/qhtyczogbhalqqq)

If you prefer you can contact me directly at my email lukasmonk at gmail.

**Comment by maljos** [comment]
It does not work. It gives the same error. no problem I will wait for your next update. Thank you for your attention

**Comment by lukasmonk** [comment]
I need to know if any of these engines run on your PC.
The problem is that I don't know which of these engines works on your computer, but komodo-13.02-linux almost certainly does.
I won't be able to correct the problem without this information.
