### ISSUE TITLE
Lucas Chess on Flathub

### ISSUE THREAD

**Issue by PlatonB** [lukasmonk/lucaschessR2#13]
Building to [Flatpak](https://flatpak.org/) and hosting on [Flathub](https://flathub.org/home) is the modern way. It will be easy for the user to install, update the program. Distro-specific errors will disappear. By the way, [GNOME Chess](https://flathub.org/apps/details/org.gnome.Chess) and [CoreChess](https://flathub.org/apps/details/com.github.sakya.corechess) are already there.

**Comment by lukasmonk** [comment]
Ok.
Do you know how much work (measured in time) is needed to publish the first time and the following times?

**Comment by PlatonB** [comment]
I cannot be sure of the time required, because I have not yet built Flatpaks. I guess the most difficult thing is to write the [config](https://github.com/flathub/org.gnome.Chess/commit/a327bfba344b0bd076a89b7b93c49da4b97bf592). I hope @alexlarsson and @mwleeds will give you detailed tips.
