### ISSUE TITLE
Move commentary remains visible on the next move.

### ISSUE THREAD

**Issue by UweBlaha** [lukasmonk/lucaschessR2#131]
First of all, thank you very much for your work. Lucas Chess is great!!!
Unfortunately there has been a bug or a feature since the 2.11 version. If I comment in a game, the comment remains visible in the next turn. And so on. That wasn't the case with 2.10a. Reinstalling doesn't fix the problem. Windows 10 22H2. Thank you again.
Gruss aus Berlin Uwe

**Comment by lukasmonk** [comment]
Thank you very much
Corrected in version 2.11c.

**Comment by UweBlaha** [comment]
Perfect.

**Comment by UweBlaha** [comment]
Perfect.
