### ISSUE TITLE
Where is analysis bar?

### ISSUE THREAD

**Issue by AlexeySlvv** [lukasmonk/lucaschessR2#132]
Sorry, but I cannot find analysis bar in R2.11b on Linux. And there is no information about it on download page. Was it removed?

**Comment by lukasmonk** [comment]
The change in this version is that the analysis bar is configured, first at the general level, in the general options, (tab Appearance 2), and then on each screen where it is usable, via Config,

![image](https://github.com/lukasmonk/lucaschessR2/assets/6254278/660e7e82-a2a7-4017-a961-2a1edbfe31e3)

![image](https://github.com/lukasmonk/lucaschessR2/assets/6254278/6e7e1898-b417-4b66-bac8-afd700a9a3cd)

**Comment by AlexeySlvv** [comment]
Oh, thanks! 
The greatest chess app!
