### ISSUE TITLE
Piece drag on board rejected if variant exist

### ISSUE THREAD

**Issue by Lingepumpe** [lukasmonk/lucaschessR2#138]
When analysing my games, sometimes I use "Utilitities->Analysis" to look at each move for X seconds. Then I go through the game move by move (usually with a kibitzer running as well, but irrelevant to the report). When I am in some position P of the game, there is the move that was played in the game M, and the 3 top moves according to the engine M1, M2, M3 as "Variants".

If I drag a piece to make a move in the position P, it will not work if the move is M1 or M2 (except if it is M). It works for M3, it works for "new" moves for which no variants exist, and it works for M, but if it is variant move that is not the move of the "last" variant (M3), then it will ignore my move and instead play the first move of the last variant: M3.

Tested with R 2.12d, but existed also in previous versions. Also works with "manually created" variations.

Short reproduction:
- Create own game
- Make moves: 1. d2-d4 d7-d5
- Left arrow (back to position after 1. d4)
- Make move: 1. ... c7-c5 (works, added as variant)
- Left arrow (back to position after 1. d4)
- Make move 1. ... e7-e5 (works, added as second variant)
- Left arrow
- Try to make move (by dragging on the board) 1. ... c7-c5 (first variant move). It will ignore it and play 1. ... e7-e5 (second variant move)

**Comment by lukasmonk** [comment]
Fixed.
