### ISSUE TITLE
Ability to add variations in variation window in "Moves tree"

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR2#14]
Hi,
After analysing a position by engine, we get a list of moves in Moves tree, when we double click on "Score", a window opens which shows entire best variation chosen by engine. It would be helpful to study a position if we are able to add more variations (secondary variations) in this window. This ability can give a user 360 degree understanding of any position. Currently we can only see a single variation line here.

**Comment by lukasmonk** [comment]
https://github.com/lukasmonk/lucaschessR2/issues/7#issuecomment-1231904928
