### ISSUE TITLE
Openings : training with a book / ECO bug

### ISSUE THREAD

**Issue by jcpoux** [lukasmonk/lucaschessR2#141]
Openings : training with a book / ECO bug
The ECO is correct when the first game is saved in pgn, 
then it is incorrect because it always corresponds to the first game.
I have to close and restart the Training after each game.

**Comment by jcpoux** [comment]
That also appears on a same game if takeback.

**Comment by lukasmonk** [comment]
The problem is the reuse of an object.
I have made some changes to solve it.
Thanks.
