### ISSUE TITLE
R 2.15 Linux installer doesn't work

### ISSUE THREAD

**Issue by rchastain** [lukasmonk/lucaschessR2#148]
Hello!

The R 2.15 Linux installer doesn't work here (Linux Mageia 64-bit). The installer stops on 45% and no longer moves.

![R_2_15](https://github.com/lukasmonk/lucaschessR2/assets/13957204/2d199079-d67c-4fcf-a439-fa427dc8b578)

I tried several times. I even tried to redownload the file, without success.

Does it work for you?

(By the way, very glad to see _Alouette_ back!)

Regards.

Roland

**Comment by lukasmonk** [comment]
I have tried it and there have been no problems.
Could it be a space problem?

I have added Alouette on Windows. On Linux I have not been able to update it (0.1.4 -> 0.1.7), because it uses a higher GNU libc version than the rest of the program.

**Comment by lukasmonk** [comment]
Roland, I have compiled Alouette on the Linux I use as a base and it worked, so I will update the Linux version to 0.1.7.

**Comment by rchastain** [comment]
> Roland, I have compiled Alouette on the Linux I use as a base and it worked, so I will update the Linux version to 0.1.7.

Very good news. Thanks!

**Comment by rchastain** [comment]
> I have tried it and there have been no problems. Could it be a space problem?

No idea. I will try on another machine tomorrow.

**Comment by rchastain** [comment]
Installation successful on another machine. There must be a problem on my main computer. I close the issue.

**Comment by rchastain** [comment]
I didn't remember how to connect to Transifex.

I would have made a little modification: `À propos` instead of `A propos` (for **About**).

And I would have translated **Fresh News** by `Actualités`. (For now it is not translated.)

**Comment by lukasmonk** [comment]
Thanks Roland. 
Notice to Eric, who is translating from French.
