### ISSUE TITLE
On wayland  I cannot install,

### ISSUE THREAD

**Issue by kryss05** [lukasmonk/lucaschessR2#15]
I use Archlinux with Gnome 42.1  (Wayland) if I want to install I receive this message: 

```
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Lucas Chess R 2.01c  100%

(setup_linux:9802): GLib-GIO-ERROR **: 11:19:39.095: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
./setup_linux.sh: line 19:  9801 Trace/breakpoint trap   (core dumped) ./setup_linux
```

If I disconnect and connect to the X11, everything goes well and works as I expected, but under Wayland it doesn't start even after it's installed with X11.

**Comment by staubsauger** [comment]
QT_QPA_PLATFORM=xcb ./LucasR --> starts fine

**Comment by kryss05** [comment]
> 

QT_QPA_PLATFORM=xcb ./LucasR
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(LucasR:16761): GLib-GIO-ERROR **: 11:52:14.426: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

**Comment by staubsauger** [comment]
So I'm on kde-wayland. Maybe that is the difference. But it is weird, cause the command only tells the program to not start in wayland instead of x... But I the program is compiled with wayland executable it should run fine without this 'hack'.

**Comment by kryss05** [comment]
`[me@archlinux ~]$ LucasR
Traceback (most recent call last):
  File "Launcher.py", line 50, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'LucasR.pyc'
[2762] Failed to execute script Launcher

**Comment by lukasmonk** [comment]
A direct tar.gz distribution, where Lucas.pyc exists:
https://drive.google.com/file/d/1AVLKFjGZkpvXePhi3pxwd4SiEu3ZJmKN/view?usp=sharing
