### ISSUE TITLE
Linux wayland native vs xwayland

### ISSUE THREAD

**Issue by Lingepumpe** [lukasmonk/lucaschessR2#157]
When I start Lucas Chess after installing on Linux, it starts in xwayland "compatiblity" mode, as can be checked e.g. by starting "xeyes": The eyes only follow the mouse as long as it is over a xwayland application, for native wayland applications the eyes are frozen.

In this compatiblity mode, I get flickering issues, e.g. when going forward/backwards in moves in a game, the move is not always executed cleanly, but flickers forwards and backwards a few times first. 

If I force LucasChessR into starting in native wayland mode, by editing `~/.local/share/applications/LucasChessR.desktop` and changing the Exec line into `Exec=env QT_QPA_PLATFORM=wayland /home/myuser/LucasChessR/bin/LucasR`, then the flickering disappears, but I have a new issue: I cannot paste (Ctrl+v) copied PNGs or FENs into the board to quickly load games or positions anymore - nothing happens when I press Ctrl+V.

**Comment by lukasmonk** [comment]
I have not been able to replicate it in a virtual machine with Ubuntu.

**Comment by Lingepumpe** [comment]
The issue no longer occurs to me either, I freshly installed Ubuntu 24.04 and LucasChess. LucasChess now starts as native wayland application without any invocation tricks, and pasting works.
