### ISSUE TITLE
Feature: ADDITION: Columns in Games Database Menu

### ISSUE THREAD

**Issue by tidypy** [lukasmonk/lucaschessR2#159]
Addition of EVAL, and Opening Code to the Grid. 

![2024-09-20 11_56_59-UserData_Databases_d4-all-out-safe lcdb](https://github.com/user-attachments/assets/22d7a8bd-fc6f-414c-bcd2-e781e9fbb2b0)

Reason Case: 
Sorting or filtering by Advantage, Sorting or filtering by ECO Code AND OR Advantage. 
Allows user to retain data even if Engine tournament parameters were improperly set. 
Example: Allows filtering for Pattern of play in specific Openings that result in endgame advantage after move 50.

**Comment by lukasmonk** [comment]
The analysis populates the ECO and Opening columns.
The analysis can be configured to add Accuracy fields.

**Comment by tidypy** [comment]
Thank you.
