### ISSUE TITLE
tutor takes always 100% cpu regardless of the time limit

### ISSUE THREAD

**Issue by davidenitti** [lukasmonk/lucaschessR2#16]
when I activate the tutor e.g. Stockfish_15_x6, it always takes 100% cpu regardless of the time limits.
is there a way to fix this?

**Comment by lukasmonk** [comment]
![image](https://user-images.githubusercontent.com/6254278/174158137-7e287ced-c8a3-457d-82b5-908cff69d09d.png)

**Comment by davidenitti** [comment]
thanks! it worked.
how come when the background option is enabled it does not follow the given duration?

**Comment by lukasmonk** [comment]
This is considered a minimum.
Another option to take into account is the number of threads.
![image](https://user-images.githubusercontent.com/6254278/174160123-e646910f-292c-481d-b7bd-4cda2727c1bc.png)
