### ISSUE TITLE
No Trainings Created : Lack of Data

### ISSUE THREAD

**Issue by tidypy** [lukasmonk/lucaschessR2#161]
STEPS:  
Ran Engine Touranment
Save to Database
Open Database .lcdb
Filter Games
Select All Games
1. EXPORT
2. Create Training --> "Play Like Grandmaster"
3. Set parameters as POP-UP requested  = 300+ games selected. 
4. ERROR "Not Enough Data" No Trainings Created.  Yet 300+ games

I've tried many different methods; this was my intended "Ideal" method to create a training.  

REASON:  
Create a training from engine level play, with specific response, filter for winning outcomes, train for pattern play. 
EXAMPLE:   
Rybka parameters are set for Contempt of position, prefer bishops, Desired opening set, ---> Desired FEN or similar endgames acheived, --> Play like Grandmaster. 
Example intention:  (learn to use bishop pair against rook, using engine to preserve bishops during middlegame when possible, complete the endgame from the pawn structure created out of Colle System for example. may learn preserving bishops is decisive against 2300elo but not at 2600elo.)

![ttainingcreate2024-09-20 12_21_13-UserData_Databases_d4-all-out-safe lcdb](https://github.com/user-attachments/assets/f33fd6b6-776f-4b99-b5b2-fbdfa60dcfc3)
![noTrainingsLackData-2024-09-20 12_20_25-UserData_Databases_d4-all-out-safe lcdb](https://github.com/user-attachments/assets/bd21ab2b-8d3e-4db8-8f2f-8404df55bea6)

**Comment by lukasmonk** [comment]
The process does not consider the items with FEN included other than the initial one. The fen included in these items, for some reason, does not consider it as an initial fen.

**Comment by tidypy** [comment]
Yup;  If a custom "Initial Position" is selected, seems to break 'Training Creation' later.
