### ISSUE TITLE
[Feature Request] Engine opponent configurations to Main Toolbar ("Play")

### ISSUE THREAD

**Issue by TapioOfTapiola** [lukasmonk/lucaschessR2#163]
Hi,

I am refering to: "Play against an engine" - "Save/Restore"

Can you place those configurations, for quick access, directly under the main toolbars "Play" menu? I think it would be valuable. More emphasis on playing, no itch to do tinkering in the "Play against an engine" window :-)

Thank you, great software

**Comment by lukasmonk** [comment]
Good idea. I have made a first attempt for the next update.

**Comment by TapioOfTapiola** [comment]
I re-opened. Maybe there's more ideas to this. I thought the maintainance could be up front, more visible, also the renaming of presets is not obvious. I noticed it instantly is possible via a right click on an entry.

That aside, many thanks, it's very good stuff.

**Comment by TapioOfTapiola** [comment]
I think it's buggy. I had a preset "Stockfish" which showed the wrong engine. Renamed it, loaded it, changed engine. But there is no way to save that entry. Also there is no way to create a new preset.

Another thought was, now that another option could be "Color: Ask at game start" - where only then it could offer Black/White/rnd.

**Comment by TapioOfTapiola** [comment]
OK, in maintainance, "New" wasn't visible for me at first, because window too small. Will test now.
