### ISSUE TITLE
Adding variations arrows to main board doing kibitzing

### ISSUE THREAD

**Issue by VarunBatraIT** [lukasmonk/lucaschessR2#166]
At the moment, a really tiny board appears. Can it happen like in chessx?

**Comment by lukasmonk** [comment]
I have no idea, I don't know chessx. Alt B brings up the chessboard configuration options. Or by clicking in the top left corner

**Comment by VarunBatraIT** [comment]
![image](https://github.com/user-attachments/assets/bae32283-43f1-4792-9b5a-b6cf43aa3dae)

Hi thanks a lot for a quick revert.

I believe I was horribly unclear. Please note the small board which has appeared when I clicked on kibitzing in above image.

So far I did following:

1. I opened a game i.e. PNG.
2. I ran an auto analysis. 
3. Once, it was done, I opened kbitzing (I think point 2 was unnecessary for the screenshot)

The arrows are appearing in a small board. Can you please allow them to be moved to main board? 

Some apps also provide multiple arrows - broader for highly recommended moves and narrower for others (lichess)

Some apps also provide 2nd and 3rd move as well like droidchess - so for even there is one mainline in analysis, it will give arrows further as well so - move 1, move 2, move 3, move 4 all from mainline.

**Comment by lukasmonk** [comment]
I will study it.

**Comment by VarunBatraIT** [comment]
This is the feature I was talking about as multiple arrows:

This is laptop app. (Windows,Linux)
https://banksiagui.com/multi-thinking-arrows/

This is android app.
https://github.com/peterosterlund2/droidfish/blob/master/README.md#arrows

**Comment by VarunBatraIT** [comment]
![droidfish-multi-arrow](https://github.com/user-attachments/assets/5e26e889-8800-4cb2-8f36-6595b94a5597)

**Comment by VarunBatraIT** [comment]
Thanks for directing to the world of multi-arrow. This is fantastic. I saw that when I tried that version. 

I hope to see something like this implemented in kibitzer as well i.e. Multiple Arrows.
