### ISSUE TITLE
configurable click style

### ISSUE THREAD

**Issue by snuggles4553** [lukasmonk/lucaschessR2#169]
Hi,

sometimes I wish there was a way to disable mouse moves made by clicking.

It has happened a couple of times in games against the computer that I made a move just because I was clicking on the board (for example to make the 'last move highlight arrow' disappear I sometimes double click the board), **unaware that I had clicked a piece before, and hence a piece got moved, thereby making the wrong move (which is impossible to undo in some game modes) and blundering**.

It would be helpful if either of the following were possible:

  * Configure the "move style":
  I suppose there are 3 variants: "move by click + move by drag and drop" or "move by click" or "move by drag and drop". This is what I would love to have. You could leave it at the first option by default, and users like me could set it to "move by drag and drop".

  * And (perhaps, optionally...) make it possible to enable a selection indicator, so you know when a piece is selected.

Thanks in advance for considering this! :heart:

**Comment by lukasmonk** [comment]
The options are "Drag and Drop" and one of the:
![imagen](https://github.com/user-attachments/assets/7d077cf7-3116-41d3-9765-2036250949cf)

or with keyboard:

- Coordinates: g1f3 
- PGN: Nf3

**Comment by lukasmonk** [comment]
Added option to the next update.
