### ISSUE TITLE
Kibitzer overloaded when moving quickly through a game

### ISSUE THREAD

**Issue by Lingepumpe** [lukasmonk/lucaschessR2#170]
When I analyze a game, I typically start the kibitzer engine at the side, and then go through the moves with the arrow keys. If I fast forwards through the game by keeping the arrow key pressed down for a few moves (e.g. fast forwarding to move 40 of the game), the moves are played out quickly on the board as expected, but the Kibitzer seems to get a huge backlog of positions it should look at, so my position might already be at move 40, but the kibitzer is looking at move 10 then 10.5, then 11, then 11.5. It takes a while of waiting for the kibitzer to "catch up" to the actual position on the board.

Expected behavior:
If the kibitzer is still being initialized for position 1.5, and I fast forward to 30, then we should either:
- Terminate the initializing kibitzer for position 1.5 and replace it with one for the position at move 30 [best solution, but requires aborting the kibitzer]
- Wait until the kibitzer has initialized for position 1.5, terminate it as done currently, and then move on to position at move 30, skipping the intermediate positions. (small wait, but allows the keep the current behavior of blocking the kibitzer until it has initialized and presumably terminated "cleanly").

**Comment by Lingepumpe** [comment]
See the attached short video showing it. I guess it depends on how fast you move through the moves (e.g. your keyboard repeat rate if you keep the arrow button pressed) and on your kibitzer initialization time - I am using latest stockfish.

[Screencast from 2024-11-10 11-08-24.webm](https://github.com/user-attachments/assets/8171a5f2-315e-4ec2-b9ab-a48ba45dfff9)

**Comment by lukasmonk** [comment]
Added some code to fix the problem.
