### ISSUE TITLE
Automatic Stockfish version selection doesn't recognize AVX512 on Zen 4

### ISSUE THREAD

**Issue by tooruu** [lukasmonk/lucaschessR2#173]
I'm using AMD Ryzen 7600x (Zen 4) CPU which supports AVX512 instructions, but the automatic selection picks BMI2 instead. Running version 2.17b.
![image](https://github.com/user-attachments/assets/9ee5c31c-2c39-4fa6-b361-7b3b82fcc064)

**Comment by lukasmonk** [comment]
Can you try changing a file? It's called versions.txt, and it's in:
if you have Windows.

c:\Users\<usuario>\AppData\Local\Programs\LucasChessR\bin\OS\win32\Engines\stockfish\versions.txt

Stockfish-17-x86-32.exe
Stockfish-17-x86-32-sse2.exe
Stockfish-17-x86-32-sse41-popcnt.exe
Stockfish-17-x86-64.exe
Stockfish-17-x86-64-sse3-popcnt.exe
Stockfish-17-x86-64-ssse3.exe
Stockfish-17-x86-64-sse41-popcnt.exe
Stockfish-17-x86-64-avx2.exe
Stockfish-17-x86-64-bmi2.exe
Stockfish-17-x86-64-avxvnni.exe
Stockfish-17-x86-64-avx512.exe
Stockfish-17-x86-64-vnni256.exe
Stockfish-17-x86-64-vnni512.exe

Change it to:

Stockfish-17-x86-32.exe
Stockfish-17-x86-32-sse2.exe
Stockfish-17-x86-32-sse41-popcnt.exe
Stockfish-17-x86-64.exe
Stockfish-17-x86-64-sse3-popcnt.exe
Stockfish-17-x86-64-ssse3.exe
Stockfish-17-x86-64-sse41-popcnt.exe
Stockfish-17-x86-64-avx2.exe
Stockfish-17-x86-64-bmi2.exe
Stockfish-17-x86-64-avx512.exe
Stockfish-17-x86-64-avxvnni.exe
Stockfish-17-x86-64-vnni256.exe
Stockfish-17-x86-64-vnni512.exe

The line with `Stockfish-17-x86-64-avx512.exe` is one position higher.

[versions.txt](https://github.com/user-attachments/files/17841635/versions.txt)

And say me the result, please.

**Comment by tooruu** [comment]
Worked like a charm! Do I have to change this line on every update?

**Comment by lukasmonk** [comment]
Great!

> Worked like a charm! Do I have to change this line on every update?

Of course not, I have to do it myself in the development version, for the next update.
