### ISSUE TITLE
Can I save positions from Challenge 101?

### ISSUE THREAD

**Issue by Puxap-3opre** [lukasmonk/lucaschessR2#176]
Sometimes the chess problems at the start ("Challenge 101") have interesting positions which I'd like to analyze further. But any key press is intercepted, so I can't even make its screenshot, and any mouse click destroys the position. I'd like to be able to somehow save the current problem from those "10 challenges", or to somehow import/open it as a "custom position" to fiddle with it.

Thank you! Lucas Chess is the best!

**Comment by lukasmonk** [comment]
It is possible now, because they are recorded as they are made:
![imagen](https://github.com/user-attachments/assets/243d5b02-f2b9-45c1-a062-6d3a5f35621b)

**Comment by Puxap-3opre** [comment]
Thank you. I guess I should close this issue now.
