### ISSUE TITLE
Reading PGN with a new window

### ISSUE THREAD

**Issue by Arunachala-Ramana** [lukasmonk/lucaschessR2#18]
Hello there.

In order to read a PGN file, **i always have to be root** (Using ubuntu) and also pgn opens only in a new window. The previous feature was fine where you just paste the pgn and analyze it. 

Kindly help.

**Comment by lukasmonk** [comment]
This must work in Ubuntu 22.04 : https://drive.google.com/file/d/1RpyDenar14faAjnrENa9gTQ7apD0qNHP/view?usp=sharing
