### ISSUE TITLE
Clean uninstall to re-install

### ISSUE THREAD

**Issue by bprijadi** [lukasmonk/lucaschessR2#181]
Hi Lucas, sorry if I write this as a question rather than an issue - because this could be a question that not only I myself have and I don't know which forum to ask. How do we clean un-install Lucas Chess to Install the latest version with its new dependencies and libraries? Does it apply to all platforms (windows, Linux, portable and installable)? Thanks! - Budana

**Comment by lukasmonk** [comment]
The UserData folder contains all the data accumulated by the user. I advise to copy this folder to another location as a backup.
All other folders (bin/Resources) can be deleted, unless the user has copied something into them.
In Windows, if it is an installation, this is done via the uninstall option.
One option is to rename the LucasChessR folder, to LucasChessR.old, then install the new version, and copy UserData from .old into LucasChessR. (both work independently by running LucasR.exe/LucasR.sh in their respective folder.)

**Comment by bprijadi** [comment]
Awesome. Best chess GUI ever.
