### ISSUE TITLE
Text in Director (Abc) doesn't work

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR2#19]
Hi,
Option F10 in Director is not functioning. When you click it, it is added (Text) but when you save it and close the window, it disappears. When you reopen Director, that same entry is also missing there. I am using it first time, so don't know whether it's a bug or I am missing something.

**Comment by lukasmonk** [comment]
Yes, it is a bug, I take note.

**Comment by lukasmonk** [comment]
Fixed in the next update
