### ISSUE TITLE
Elo calculation in analysis

### ISSUE THREAD

**Issue by franissirkovic** [lukasmonk/lucaschessR2#2]
It seems to me that elo-estimation doesn't work properly during the analyze (at least it works differently than previous version).
I would guess that average elo is attached to a move (average of all previous moves). In effect, later moves have smaller effect in that case.
For example, move 12 with diff 1.11 gets elo 2992, and move 46 with diff 1.48 gets elo 3481.

Best wishes, Franis Sirkovic.

I have made a mistake, i have added this bug as a comment on another issue, apology.

**Comment by lukasmonk** [comment]
I don't like the way elo is currently calculated, I'm working on a change in the formula.
