### ISSUE TITLE
How to resize board?

### ISSUE THREAD

**Issue by pstein** [lukasmonk/lucaschessR2#22]
How can I resize the chess board.

Resizing with mouse at the corner is disabled here

**Comment by pstein** [comment]
Oh I see: the tiny wrench symbol

Any reason to move it out from settings?
In v1.1.3 it was part of Settings

**Comment by lukasmonk** [comment]
The answer of [XI64](https://github.com/XI64) is the correct. There is another way too and that is with Ctrl and the mouse wheel on any board.

`Any reason to move it out from settings?`
Is this what you mean?
![image](https://user-images.githubusercontent.com/6254278/183040743-37a07231-7502-4b39-836f-394f1f3f551d.png)

**Comment by pstein** [comment]
No, I would like to click on toolbar symbol "Options" and get all the sub menus from the wrench symbol.

But I miss e.g. "Pieces", "Board size",....

**Comment by lukasmonk** [comment]
It is a current board dependant menu.
Alt B is other way to launch it.

**Comment by pstein** [comment]
If it is offered in the Wrench menu it should be available in "Options" menu too.
So it is (should) NOT board dependent

**Comment by lukasmonk** [comment]
Actions of the menu are board-dependent.
There are many different boards in the program, each one has its own configuration, and there is no "Options" menu in all of them.
