### ISSUE TITLE
Are there any other GUI Themes?

### ISSUE THREAD

**Issue by pstein** [lukasmonk/lucaschessR2#23]
Are there any other GUI Themes (e.g. shapes of the figures and board colors?

**Comment by XI64** [comment]
For Chess board colors, click on the faded `wrench` symbol in the corner of the chess board, then click on `Colors` and pick accordingly or click `edit` to further customize. 
Alternately, the same can be opened by going `Options -> Colors -> Main Board`.

To change the pieces, again click on the `wrench` symbol in the corner of the chess board, then click on `Pieces`. Alternately, the same can be opened by going `Options -> Colors -> Main Board -> Other Options Pane at the top right -> Pieces drop down`
