### ISSUE TITLE
Null moves support for PGN files ? 

### ISSUE THREAD

**Issue by XI64** [lukasmonk/lucaschessR2#26]
I am not sure if LucasChess already supports null moves, so far I cannot figure it out how to make lucaschess parse it hence the feature request.

-----

I currently have a "patched up" PGN file (where I basically joined two lichess games into one) and it has a weird move. `13...Rb8` , where the `..` after `13.`  is called a `null move` which is what I found searching over the internet. The *other* GUI (SCID vs PC) can infact read this when the `..` is replaced with `--` and can continue thereon. 

However doing the same with lucaschessR2 resulted in a split in the temporary database view, where the first game has no moves altogether and the second game has the moves uptil the `null` is encountered.

So far on [searching](https://chess.stackexchange.com/questions/21412/chess-gui-that-allows-null-moves), I found out that a few many GUIs support null moves, including lichess & chesscom. So I am curious if lucaschess will also provide some support for it. Thanks!

Small point but by default SCID cannot read `..` and will complain about an error. I hope lucaschess' implementation would support both `..` and `--` if implemented.

P.S. Big fan of your lucaschess and your work!

**Comment by lukasmonk** [comment]
It is not supported.
It's not easy to implement, I imagine it will have a lot of side effects.
I will look into it.
