### ISSUE TITLE
Lichess Puzzle Database import takes forever.

### ISSUE THREAD

**Issue by Yaetrna** [lukasmonk/lucaschessR2#27]
I tried to import the latest Puzzles from the Lichess Database into a Lucas Chess Database but the Import takes forever.

I've tried copying a small amount of Puzzles out of the 2.9M Puzzle File and put it into a new .csv File but it still takes forever.

This is how it looks like:
![grafik](https://user-images.githubusercontent.com/104841365/183283738-8f34c852-e217-49fe-88c4-fac1037ce3c4.png)

**Comment by lukasmonk** [comment]
In the program folder, subfolder bin, there is a bug.log file, it is a text file, the last lines probably show the problem, if you send it, I will check it.

**Comment by lukasmonk** [comment]
I have seen what the problem is.
The lines must have 9 fields, some have more or less. 
I have corrected it in the program, 
If you replace the .pyc file in bin/Databases, I think it will work.
[Databases.zip](https://github.com/lukasmonk/lucaschessR2/files/9276561/Databases.zip)
