### ISSUE TITLE
Limit Engine's Strength

### ISSUE THREAD

**Issue by saint2706** [lukasmonk/lucaschessR2#28]
I try to set the UCI_LimitStrength parameter of stockfish but the config doesn't actually get saved and used.

**Comment by lukasmonk** [comment]
In which context/option/window?
Have you activated the engine log saving, so that you know which engine is using this parameter?

**Comment by lukasmonk** [comment]
Some days ago I have changed my code in relation to this window, in September I will publish an update with this fixed.
In any case, limiting the tutor's knowledge does not seem a priori a good idea, I suppose you have a good reason.
