### ISSUE TITLE
Unable to run LucasChessR2

### ISSUE THREAD

**Issue by Arunachala-Ramana** [lukasmonk/lucaschessR2#29]
Kindly help. Getting the following error. 
![Screen](https://user-images.githubusercontent.com/68316708/185600341-afb39151-ac8f-468e-a548-dc8033c2bfd4.PNG)

**Comment by lukasmonk** [comment]
I have no idea.
Maybe exec with sudo, solve the problem.
Also the .sh file can have the next args:
`--keep : Prevent the files to be extracted in a temporary directory that will be removed after the embedded script’s execution. The files will then be extracted in the current working directory and will stay here until you remove them.

--noexec : Do not run the embedded script after extraction.
`
if you keep the files, you can run Lucas directly.

**Comment by Arunachala-Ramana** [comment]
Executing with sudo does help.

**Comment by lukasmonk** [comment]
Other solution: https://askubuntu.com/questions/1425165/lucaschess-wont-start-or-install-after-update-to-22-04-claiming-no-antialiasin
