### ISSUE TITLE
Check for updates always errors out

### ISSUE THREAD

**Issue by TadhgEomonn** [lukasmonk/lucaschessR2#3]
Using the check for updates option no longer works. It always reports the error message: Encountered a network problem, cannot access the Internet.

This used to work for me (unless my internet connection was down) prior to version 2.00+.

**Comment by lukasmonk** [comment]
There is no update from version 1.3 to version 2, it needs an installer.

I have just uploaded version 2.1

**Comment by TadhgEomonn** [comment]
I understand that updating from version 1.3 to 2.0 required a separate download.

My issue was with version 2.00c and the same thing holds for version 2.01: checking for update from within the program always errors out with "Encountered a network problem, cannot access the Internet." The program is no longer capable of checking for updates.

**Comment by XI64** [comment]
> I understand that updating from version 1.3 to 2.0 required a separate download.
> 
> My issue was with version 2.00c and the same thing holds for version 2.01: checking for update from within the program always errors out with "Encountered a network problem, cannot access the Internet." The program is no longer capable of checking for updates.

Are you using any fancy network blockers (like simplewall or tinywall)? If so you might need to allow lucaschess. Also antivirus programs can interfere so make sure that is not the case here.

**Comment by TadhgEomonn** [comment]
I am no longer experiencing problems with automatic update. Thanks for solving my problem.

teroche

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
