### ISSUE TITLE
doesnt support windows 7?

### ISSUE THREAD

**Issue by ahahahaah** [lukasmonk/lucaschessR2#30]
hello,
the lucasr.exe file crashes when launched.
i suppose its because i have windows 7 
is there a version compatible with my os? (win7 pro 64bits)
thx

**Comment by lukasmonk** [comment]
Yes, it is compatible with windows 7. I haven't tested it for a while, but there have been no changes in the executable either. 
The python version used is 3.7 because it is compatible with W7.

**Comment by ahahahaah** [comment]
it is compatible? then i dont understand why it crashes when i launch it. 
there is something else that i have to install on my computer? python is integrated in the lucaschess program or have i to install it separately?

**Comment by lukasmonk** [comment]
All the python libraries go with the program, it is not necessary to install python.
In a virtual machine with W7 pro 64 bits, I just installed the program, and it works.
I don't know what the problem could be, maybe if the installation has been done for all users, and it doesn't work with sufficient permissions. I can't think of a good reason.

**Comment by ahahahaah** [comment]
i dont install it, i prefer the portable version
maybe this can help to see what's wrong?
![image](https://user-images.githubusercontent.com/69671446/187074457-330e1cc5-96b7-484a-9f92-72df76037b28.png)

**Comment by ahahahaah** [comment]
topic was closed as completed but the problem remains...
an other point to help analyze the problem is that the old version lucas 11.17 (not lucasR) is running without any problem
something has changed between lucas and lucasR ?

**Comment by lukasmonk** [comment]
It seems to be a particular problem, which I cannot replicate. It is related to the distribution of the program, and this I am not going to change.
I have not received any further incidents regarding this issue.
