### ISSUE TITLE
Lucas Chess R 2.02a not responding during Compete mode  Windows 10

### ISSUE THREAD

**Issue by tcrowell4** [lukasmonk/lucaschessR2#32]
I'm new to Lucas and have started playing in Compete / Competition with Tutor mode to get familiar.  I have experience multiple "not respondings" in almost half the games so far.   Here is the latest.

I have not tried playing just against the engine without Tutor mode yet to see if it occurs there.

![image](https://user-images.githubusercontent.com/37672199/186948875-ee3a30d1-a121-420e-a426-c54de007f5f9.png)

It has happened at Beginner Level 2 and Amateur Level 1

At first I thought it was when I responded quickly to a move but today it was after deliberating and then playing  Rde2

OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043

Lucas Chess R 2.02a

I do have python loaded on my machine as well.
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32

**Comment by lukasmonk** [comment]
The problem is perhaps the Acqua engine that locks up in some circumstances.
Please try another engine.

**Comment by tcrowell4** [comment]
Reading back through other posts I found #16 Tutor using 100%

I followed the recommendation and disabled the background tab and had no further issues without changing the engine.
