### ISSUE TITLE
Pixbuf error with import PGN

### ISSUE THREAD

**Issue by KDB2** [lukasmonk/lucaschessR2#33]
Hello,

I have installed the Linux version of Lucas Chess R 2.02a. When trying to import a PGN file with Tools > PGN > Read PGN file, Lucas Chess crashes and closes. 

`**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/emmanuel/.icons/Mint-Y-perso/mimetypes/16/image.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/emmanuel/.icons/Mint-Y-perso/mimetypes/16/image.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Abandon (core dumped)
`

I tried to revert to Adwaita icons, same issue. I move the icons in my home folder, same issue. If I start Lucas chess using sudo, then it works. It therefore seems to be an access issue. 

I have a brand new Linux install, and I didn't install anything weird yet, or made any strange setup. My install is brand new, because while trying to solve this issue, I ended up messing the full system. Therefore I just reinstalled everything today :)

`emmanuel@emmanuel-N24-25JU:~$ inxi -F
System:
  Host: emmanuel-N24-25JU Kernel: 5.15.0-41-generic x86_64 bits: 64
    Desktop: Cinnamon 5.4.11 Distro: Linux Mint 21 Vanessa
`

**Comment by lukasmonk** [comment]
The next version will use a customised system for selecting files, with the option to switch to the operating system's native mode (from Options/Configuration).
