### ISSUE TITLE
Translate is not installed in some configurations in Linux

### ISSUE THREAD

**Issue by felipealmeida** [lukasmonk/lucaschessR2#34]
Translate is sometimes not installed because if in Gui.py:47 returns false which means that configuration.x_translator is somehow true in my configuration.

I'm using Arch Linux x86_64.

Changing:

```
diff --git a/bin/Code/MainWindow/Gui.py b/bin/Code/MainWindow/Gui.py
index bbfec9c..51da803 100644
--- a/bin/Code/MainWindow/Gui.py
+++ b/bin/Code/MainWindow/Gui.py
@@ -43,7 +43,8 @@ def run_gui(procesador):
                     Usuarios.Usuarios().save_list(list_users)
 
     # Comprobamos el lenguaje
-    if not configuration.x_translator:
+    #if not configuration.x_translator:
+    if True:
         if user:
             conf_main = Configuration.Configuration("")
             configuration.x_translator = conf_main.x_translator
```

Makes the app run.

OT: I'm trying to create a PKGBUILD for Arch Linux to compile and install lucas chess R2.

Kind regards and thanks for your effort on this project.

**Comment by lukasmonk** [comment]
I don't understand what the problem is, I have not been informed of any error in this part of the program.
The language change is done from Options/Configuration.

This part of the program,  is launched in the first installation, when the translation language is not defined.

**Comment by felipealmeida** [comment]
Sorry, I should have been more descriptive.

By "install" I mean calling Code.Translations.Translate.install.

Not really installing in the system. I'm using it in-tree.

I'll investigate it better ASAP.
