### ISSUE TITLE
Personalities Not Saving

### ISSUE THREAD

**Issue by thespoilergirl** [lukasmonk/lucaschessR2#35]
I'm using a Windows 11 Computer and version version R 2.02a 

It appears that if you create a Personality from the Advance tab in the Play against an Engine Section. If you later close and restart Lucas chess, that Personality that you setup is no longer available.

![before](https://user-images.githubusercontent.com/71832480/189834733-3252d19c-05ed-46e2-b632-9ce366decda3.png)

If I then close and restart lucas chess 

![after](https://user-images.githubusercontent.com/71832480/189834731-f988cc74-2594-41fb-83e0-1aaa296d3a29.png)

As you can see there is no Test Personality anymore.

Am I doing something wrong?

**Comment by lukasmonk** [comment]
It will be fixed In the next update.
