### ISSUE TITLE
Engine Tournaments Not Working

### ISSUE THREAD

**Issue by texium** [lukasmonk/lucaschessR2#36]
When creating matches, there is nothing. No matter what count of rounds, nothing is generated. It doesn't even lag when creating hundreds or thousands signifying it's not even trying to make any.
Also, when opening an older one, with existing matches, it shows blank matches, with no data and the past records in that one are also blank, it says games were played and can be, but it just freezes when I add a helper.

**Comment by lukasmonk** [comment]
I will try to fix it today.
