### ISSUE TITLE
Better GM Personalities

### ISSUE THREAD

**Issue by texium** [lukasmonk/lucaschessR2#37]
Utilizing Rodent-4 NNUE, you can effectively create GM profiles that play like the actual World Champions. I've done some personal testing with some personalities and a certain GM-trained NNUE, and it works really well, with over 50% move matching after 2-3 seconds per move. That's with my custom-tuned personalities, though using arena with the engine as kibitz to tune further could work. Contact me for more, as I can supply you with all the files, and there should be no problems.

**Comment by lukasmonk** [comment]
The problem is the effect on the size of the distribution.

**Comment by texium** [comment]
if you use the single gm net, you just need to adjust which personality is being used. stockfish 15, takes at least 50mb if I remember correctly. my folder with rodent nnue, and the net(20mb) is a total of 23 MB and it runs just like that.

**Comment by lukasmonk** [comment]
Stockfish at this time is an untouchable, so it cannot be compared.
From Rodent right now Rodent I and Rodent II are installed.
From Rodent II there are quite a few personalities and on the other hand it is used for a kibitzer, which is based on it.
I could try to change them all to Rodent IV, but I would need, first of all, that the personalities of rodent II work, and that the index kibitzer gives similar results.
Also, compatible 32 bits in windows and compilable to linux64 version.
