### ISSUE TITLE
Custom opening not available to engine.

### ISSUE THREAD

**Issue by keith555** [lukasmonk/lucaschessR2#38]
I'd like to create a custom opening and have an engine play exclusively that opening.  I created an opening, gave it a name and a code of X99.   I looked in _Play>Play against an engine>Initial Moves Opening_. The opening I created is not there. 

There is also a panel for _Activate Book_, which seems to imply that I could create an openings book and have the engine use that. I cannot see how to create the openings book. The help document on https://www.devtome.com/  talks about  _Tools > Openings > Personal Opening Guide_ which I guess has now become _Custom Opening_, but what I see in _Custom Opening_ doesn't match with the screenshots or description in that document. 

There is also the 2015 document on http://omgchess.blogspot.com/ but that again doesn't match with what I see in the current version, and it seems to be aimed at training an opening rather than having the engine play it.

**Comment by lukasmonk** [comment]
Is it a single line or a set of lines?

**Comment by keith555** [comment]
It's taken from a course Chessable. It's a set of lines with variations and subvariations.

**Comment by lukasmonk** [comment]
From Custom Openings, you can save to PGN files or to a pgn.
From Tools/Apertures/Polyplot Factory, you can create one, and then import that pgn (pgns).
Create a polyplot book.
Install this poliglot book (Openings/Install...).
Play against any engine, Initial moves, Opponent's book, ....

**Comment by keith555** [comment]
It doesn't seem to like the PGN. After choosing _import_ and selecting the PGN file I exported from Custom Openings, it flashes up some kind of pop-up which instantaneously disappears. Nothing is imported.

**Comment by lukasmonk** [comment]
Contact me directly (lukasmonk at gmail), send me the pgns and I will convert them to pgns.
