### ISSUE TITLE
Internal Maia Engines playing moves instantaneously.

### ISSUE THREAD

**Issue by keith555** [lukasmonk/lucaschessR2#39]
I've tried both the 1500 and the 1600. The settings I have are
Fixed Time in Seconds 0.0
Fixed Depth 0
Total Minutes 20
The engine plays its moves instantaneously. Its clock remains at 20 minutes.

I downloaded lc0 and Maia and installed them as an external engine.  It does now play properly, using its allocated time, but I'm not sure if it's playing at the correct strength. The Maia documentation says that the Nodes parameter needs to be set to 0. I don't know where to set that in the Lucas Chess engine configuration page. There is a setting for _NodesPerSecondLimit_. Is that the parameter that needs to be set to 1 so that the engine will play at the rating governed by the weights file?

I also have a question regarding the _Nodes used with Maia engines_ setting on the "more" tab.  Its default is 1, but the other setting is "_From 1 (1100) to 450 nodes (1900), similar strength as other engines_". So that sounds as though it needs to be set depending on which engine you're using, but it seems to be a global setting, not a per-engine-setting.

Thanks for your help.

**Comment by lukasmonk** [comment]
Maia as config authors= Nodes 1, no time to consider.  

Lc0 is included with the distribution.

I have added From 1 (1100) to 450 nodes (1900), similar strength as other engines, to have a chance when playing against to the engines of that elo, such as Cdrill with Maia 1800.

But 1 node is the official configuration to play against human. If it is annoying that your movements are immediate, there is an option to humanize them.

![image](https://user-images.githubusercontent.com/6254278/195188639-bdddec10-2360-4459-9741-97917687aea3.png)

**Comment by keith555** [comment]
Thanks for the reply. I don't quite follow why the second option is necessary. If nodes is set to 1, and I play against, say, Maia 1500, then it will play at 1500. So when would the second option be used?  If I wanted to play at 1800, why not just the Maia 1800 engine?

**Comment by lukasmonk** [comment]
If you don't find it necessary, don't change the option and there will be no problem.
If you get tired of beating Maia 1900, and you want a little more power in the engine, with the same style, you can try the other one.
