### ISSUE TITLE
Fisher Random / Chess960 support

### ISSUE THREAD

**Issue by Lingepumpe** [lukasmonk/lucaschessR2#41]
It would be great if Chess960 PNGs and FENs would be readable by Lucas chess - I would like to analyze my 960 games using Lucas Chess!

Example FEN:
b3nnkr/pq1p1pp1/1b6/1P2p2p/P6P/1P2NN2/5PP1/BQ1B2KR b Hh - 0 10

Example PNG:
[Carlsen, Magnus_vs_Nakamura, Hikaru_2022.10.27.pgn.gz](https://github.com/lukasmonk/lucaschessR2/files/9893186/Carlsen.Magnus_vs_Nakamura.Hikaru_2022.10.27.pgn.gz)

**Comment by texium** [comment]
I was thinking exactly the same

**Comment by lukasmonk** [comment]
It is not something easy to develop, and I have been asked quite a few times, I guess I will include it eventually, but I don't know when, there are many pending problems to solve in the program, and other ideas I have on the list before.
