### ISSUE TITLE
Save database as csv

### ISSUE THREAD

**Issue by amalrajjs** [lukasmonk/lucaschessR2#46]
Need to save database in csv. Is there any way?

**Comment by lukasmonk** [comment]
Database are sqlite files: [explanation](https://www.sqlitetutorial.net/sqlite-export-csv/)

**Comment by amalrajjs** [comment]
Thanks for the reply. I want to import from Lichess Puzzle database (it contains UCI chess moves) and export it with SAN chess move notations. I have successfully import csv file and LucaschessR2 showing the SAN moves on the right hand side of database under the board with FEN position. But when I use SQLiteStudio to export csv from that lcdb database, it doesn't contain any moves (both UCI and SAN moves doesn't showing). How can I export the games along with SAN move notation?

**Comment by lukasmonk** [comment]
It is too specific and I can't include it in the program for the moment.
If you want I'll send you a python miniprogram to do it, and if you have too much trouble with this I'll send you a link to the csv with that column added.

**Comment by amalrajjs** [comment]
Sorry, I don't know coding. I think this is an easy task for you. For example, e2e4 c7c5 is in GUI moves for Sicilian defense. It's SAN moves is e4 e5. I checked other software in web, no one can convert the moves from GUI to SAN. Some supports GUI, but there isn't any trace of SAN moves. But LucaschessR2 reads csv database and showing SAN moves on right side under the chessboard. It's (SAN moves) in there somewhere. Can you add that moves in the database? I think only you can solve my trouble. You helped me to use SQLiteStudio to create csv from LucaschessR2's lcdb database. But the moves are missing. Can you add the moves seen on right side under the board to a new colum of lcdb database? Then that's solve my problem perfectly.

**Comment by lukasmonk** [comment]
I´ll try it to the next update.

**Comment by amalrajjs** [comment]
Thank you so much

**Comment by amalrajjs** [comment]
![Capture](https://user-images.githubusercontent.com/44720539/201524035-6daecfbc-8a0f-49fa-a3db-3998ad32eda8.JPG)
Adding one picture for additional clarity which I couldn't add to my previous replies. In this picture, if you can add the moves highlighted in the red rectangle as a column in the lcdb database will solve my problem.

**Comment by lukasmonk** [comment]
In the next update:
![image](https://user-images.githubusercontent.com/6254278/201524632-6fe521dc-7578-45ab-a0d5-26cfd0476059.png)

**Comment by amalrajjs** [comment]
OMG, you already done that. Hats off 🙏. Waiting for the updates 😍.
