### ISSUE TITLE
I can't import lichess puzzle to Lucaschess

### ISSUE THREAD

**Issue by zoushenhh** [lukasmonk/lucaschessR2#47]
I found that when I was importing, lucaschess memory usage rose by 1GB and then fell back to 100MB... And the import still shows work!
Does it mean that the import failed?

**Comment by zoushenhh** [comment]
> I found that when I was importing, lucaschess memory usage rose by 1GB and then fell back to 100MB... And the import still shows work! Does it mean that the import failed?

import lichess puzzle

**Comment by lukasmonk** [comment]
No, I'm doing the import on my computer and it doesn't reach 520Mb. That means that depending on the operating system it uses more or less memory, and I can't think of a way to fix it.
In my windows:
![image](https://user-images.githubusercontent.com/6254278/200187666-5f4b2c98-cc97-488d-a13a-e12d51a64e37.png)

If the process has stopped, some of the puzzles have been imported, and are valid to work with.

**Comment by zoushenhh** [comment]
I found the reason why I couldn't import it, because I was using bandzip to decompress Puzzle, not 7-zip.

**Comment by zoushenhh** [comment]
> No, I'm doing the import on my computer and it doesn't reach 520Mb. That means that depending on the operating system it uses more or less memory, and I can't think of a way to fix it. In my windows: ![image](https://user-images.githubusercontent.com/6254278/200187666-5f4b2c98-cc97-488d-a13a-e12d51a64e37.png)
> 
> If the process has stopped, some of the puzzles have been imported, and are valid to work with.

I found the reason why I couldn't import it, because I was using bandzip to decompress Puzzle, not 7-zip.

**Comment by lukasmonk** [comment]
Thanks for the information.
