### ISSUE TITLE
Kibitzer engine calculates for wrong position when opened in variation

### ISSUE THREAD

**Issue by Lingepumpe** [lukasmonk/lucaschessR2#48]
Reproduce:
1) Tools -> Create your own game
2) play 1. d4 d5
3) Go back to position after 1. d4 (e.g. left arrow)
4) play 1. ... e5 (it opens as a variation)
5) open kibitzer: Utilitites -> Kibitzers -> your_engine.

Expected: Kibitzer calculating for current position on board (1. d4 e5)
Observed: Kibitzer calculating for "main line" position (1. d4 d5)

**Comment by lukasmonk** [comment]
Fixed in the next update.
