### ISSUE TITLE
Wrong color pieces in "Result of analysis" window

### ISSUE THREAD

**Issue by ratmice** [lukasmonk/lucaschessR2#49]
In the All moves/White/Black tabs of the "Result of anyalysis" window, it appears that the pieces in the "move", and "best move", columns display white pieces for both black and white moves.

**Comment by lukasmonk** [comment]
Thanks, it is fixed in the current 2.05 beta.

**Comment by ratmice** [comment]
I was able to confirm this is fixed so closing, In order to build/test it I needed an unrelated patch that I posted in #60 though
