### ISSUE TITLE
"Check for updates" returns network problem error

### ISSUE THREAD

**Issue by cshancock** [lukasmonk/lucaschessR2#5]
Error occurs on Microsoft Windows 11 Home 

![image](https://user-images.githubusercontent.com/41805585/163728651-8d999514-eb2b-400d-93e5-00d8c045dd49.png)

**Comment by lukasmonk** [comment]
The program makes a simple call to the lucaschess web address on the internet, if for any reason the system does not allow it, it is not something that can be solved in the program, or at least I don't know what the way would be.
