### ISSUE TITLE
Adding a user hangs the program

### ISSUE THREAD

**Issue by jonathancolledge** [lukasmonk/lucaschessR2#50]
I have two users. I click on one (or I can click on select your user), then go to Options, then users, and it stops responding. Can you please help?
Edit: latest version btw

**Comment by lukasmonk** [comment]
I have not been able to replicate the problem.
What OS do you work with?

**Comment by jonathancolledge** [comment]
I'm so sorry about this. It was user error - I am so silly. The user dialogue box was hidden off the screen of my monitors. Win+shift+arrow brought it back.
