### ISSUE TITLE
package as a appimage

### ISSUE THREAD

**Issue by 9glenda** [lukasmonk/lucaschessR2#52]
It's unclear what the shell script is doing and I don't want it to mess with my /bin or /usr/bin. Especially on nixos GNU/Linux it's not a good idea to install something in /bin. not sure rather it's actually doing that but an appimage would be easy to execute without changing stuff in the system

**Comment by lukasmonk** [comment]
I have no idea how to make an appimage, and this is not a priority, because there is already a solution.
The installation is in the current user, neither /bin nor /usr/bin, only in /home/<user>/lucaschessR.
