### ISSUE TITLE
ALOT of new issues with this new in app patch on windows

### ISSUE THREAD

**Issue by texium** [lukasmonk/lucaschessR2#53]
1. My theme is locked to i think windows, i use fusion but nothing changes
2. The application takes forever to run because for whatever reason, it starts of leela zero and komodo a few times in the background before opening takes at least a minute.
3. Hiding some UCI options that used to be visible previously.

**Comment by lukasmonk** [comment]
1. What theme do you mean when you say "my theme"?
2. The application does not open anything when it starts. Please be more precise.
3. Which UCI options, which engine?

**Comment by texium** [comment]
1. in the settings the app themes, windows Vista, windows or fusion
2. I have task manager open, it opens several engines in the background
before starting.
3. My engine is Rodent with NNUE, and the uci options that disappeared
relate to the scale of nnue and the scale of classical eval

**Comment by lukasmonk** [comment]
1. The influence of selecting one style or the other is minor, but it does have some influence. It is more important the light or dark mode. 
2. The program only opens what you decide you want to open. I guess you are talking about when you play against an engine. When you decide which tutor to use or you are not using the tutor or which engine to play against, that's when you decide what engines to launch. It does not open anything that you personally have not previously decided.
3. Launch the engine from an msdos window, type uci and press return, you will get something like the following, where I don't see the options you mention.
![imagen](https://user-images.githubusercontent.com/6254278/208718193-a2e9b9cb-cfff-423f-8003-5cbd6b6bc95f.png)

**Comment by texium** [comment]
its the nnue eval and classical eval percentage

**Comment by texium** [comment]
it used to work before the update, but now it doesnt

**Comment by lukasmonk** [comment]
The problem is that those two options are wrongly composed, the number 81 and the final 23 are left over, they are a mistake, lucas chess expects 8 elements and nine come. 
I will set the limitation to at least 8 to pass this specific error.

**Comment by texium** [comment]
in response to your saying the application does not open anything, here is why it takes at least 1 minute to start, it launches several engines on my PC when I click the application
an example of what starts running when I click Lucaschess
https://i.imgur.com/ktRb7kS.png
https://i.imgur.com/XhCKBOo.png

**Comment by lukasmonk** [comment]
Yes, I was wrong, initially it checks that all engines have a file with the list of options. There was a problem with the external engines, which I have corrected for the new update.

**Comment by texium** [comment]
very glad to hear that. hope we can expect a release soon!
