### ISSUE TITLE
[bug][2.05][ui][low_prio] gui table column headers look changed

### ISSUE THREAD

**Issue by Xyrio** [lukasmonk/lucaschessR2#58]
2.05
![image](https://user-images.githubusercontent.com/2821358/209519097-75332406-f85b-4c16-901a-2590d78667e1.png)

2.04
![image](https://user-images.githubusercontent.com/2821358/209519301-421fa553-90ac-4a11-a881-80818e3b94df.png)

i updated using information -> check for updates
windows 7

**Comment by lukasmonk** [comment]
Yes, take a look to Fusion, Options/General configuration/Window style, and you have other:
![imagen](https://user-images.githubusercontent.com/6254278/209561846-d0166c0c-594a-4849-96e4-4532cf95b347.png)

**Comment by Xyrio** [comment]
kinda liked the old one better, but no big deal. fusion is good enough.

**Comment by lukasmonk** [comment]
I have added a mode = None,
![imagen](https://user-images.githubusercontent.com/6254278/209654387-aceb4a38-f192-4636-aaff-174cbea61f66.png)
