### ISSUE TITLE
lucas "R" version doesn't start for me

### ISSUE THREAD

**Issue by ahahahaah** [lukasmonk/lucaschessR2#59]
hi
i use only portable versions (no installations)

at the bottom of this page https://lucaschess.pythonanywhere.com/downloads_previous when i start the last version which is not the R version: "version 11.17" the program works.
but when i launch any of the "R" version the program crashes at the launch.

what changed in the "R" version that doesnt work with my system (win7 pro 64bits, which is considered as compatible)?
there is a note that says that the R version is not compatible with win xp, but im not even in this case.

**Comment by lukasmonk** [comment]
I have not received any further incidents regarding this issue. 
Version 11.17 is compiled with python 2.7
Version R is compiled with python 3.7
Do you know something about python? if so I can help you to find the problem because I can´t replicate it.

**Comment by ahahahaah** [comment]
no i'm not a programer.
but this means that my system has a problem with python 3.7?
do you think i can uninstall it and reinstall a "clean" version?

**Comment by Xyrio** [comment]
still same cras as in #30 ?
wild guess: try unplugging all usb?

**Comment by ahahahaah** [comment]
yeah it's the same crash
i checked the C:\Windows\System32\ucrtbase.dll
and the version is not the same as yours
mine is 10.0.14393.2247 size 998.912 Bytes

i installed some vcredist x64 from the link you give but none of them changes the version of my ucrtbase.dll

but according to what lukasmonk said, the changements from version 11.17 to version R is the Python version.
so it seems that the issue is something here, in my case.

**Comment by lukasmonk** [comment]
You could remove ucrtbase.dll from bin folder in the LucasChessR/bin folder

**Comment by lukasmonk** [comment]
Someone (Eric) told me that this was solved in his case by launching the sfc /scannow command in a cmd window.

**Comment by Xyrio** [comment]
my environment has python 3.8.9 but LucasR uses its own bundled python. and since ucrtbase.dll is also bundled it is unlikely to be the problem.

**Comment by Xyrio** [comment]
well if i rename the bin\ucrtbase.dll then lucasr.exe runs but gui never appears.

**Comment by lukasmonk** [comment]
You could copy C:\Windows\System32\ucrtbase.dll to lucasChessR\bin

**Comment by Xyrio** [comment]
yes, that is equivalent and same effect for me.

**Comment by Xyrio** [comment]
well if nothing works you can still get virtualbox and ubuntu live cd then run lucasr on linux :)

**Comment by Xyrio** [comment]
hmm seem i permanently broke all lucasr. even old 2.04 wont start now after the ucrtbase.dll experiment. even though i resotred the original file.

**Comment by Xyrio** [comment]
hmm weird there still seems to be some kind of interaction with the python version installed in the environment. i renamed my environment python.exe so it cannot be found and then it startet again.

**Comment by Xyrio** [comment]
ah nvm it was my configured external engines ( ExtEngines.pk ) somehow broke.

**Comment by ahahahaah** [comment]
thanks for trying to help.
indeed, none of these solutions work in my case.
while reading your posts i was thinking about something.

is is possible to "ignore" the integrated python of the program and force to use the python on my system? if yes, how can i do that?

**Comment by Xyrio** [comment]
doubtful but @lukasmonk might know something.

you can try to download same python 3.7 version lucasr uses and run it standalone to see if it has a problem on your system. however if 3.7 has a problem it is likely that 3.8 or other versions also have the same problem.

**Comment by ahahahaah** [comment]
i have a message that says "pip" command is unknown

**Comment by lukasmonk** [comment]
In a bat,
PATH=<folder python3.7>;<folder python3.7>\Scripts
pip install -r requirements.txt

**Comment by ahahahaah** [comment]
i dont know if it worked or not but a window opened and closed immediately
so i have tryed your next step "In the LucasChessR/bin folder: pythonw LucasR.py"
but i have a message that said pythonw is an unknown command (like it was said for the command pip)

**Comment by ahahahaah** [comment]
shit i have not installed python 3.7 (the 1st step)
let me restart, i will come back again
im idiot

**Comment by ahahahaah** [comment]
after the pip command 
![image](https://user-images.githubusercontent.com/69671446/209989910-72401bbf-b8c0-44c7-bd35-0609b3568bfd.png)

and after the pythonw command
![image](https://user-images.githubusercontent.com/69671446/209990129-7f28a615-f06f-43ed-bd1c-945ddb3769cc.png)
nothing else

**Comment by lukasmonk** [comment]
The pip command must finish without errors.
Download from https://www.lfd.uci.edu/~gohlke/pythonlibs/   psutil:
![imagen](https://user-images.githubusercontent.com/6254278/209993569-b00cf3d8-7b01-4e5b-94d6-4065ed5b4d5c.png)

then 
pip install [path file downloaded]

**Comment by ahahahaah** [comment]
i have a 64bits processor, you sure i should get the win32 version?

**Comment by lukasmonk** [comment]
Yes.

**Comment by ahahahaah** [comment]
here is what i obtain
![image](https://user-images.githubusercontent.com/69671446/210001421-4eff7b9a-0ae7-4789-a9d0-a15193b6304d.png)

**Comment by lukasmonk** [comment]
Do you have more python installed?
Go to the python3.7 folder, Scripts subfolder and try again.

**Comment by ahahahaah** [comment]
i don't find the python3.7 folder ^^
what is the normal path?

**Comment by Xyrio** [comment]
python -V
python -c "import os, sys; print(os.path.dirname(sys.executable))"

**Comment by lukasmonk** [comment]
c:\Program Files (x86)\Python37-32\

**Comment by Xyrio** [comment]
fyi: python-3.7.9-amd64.exe tried to install to my users %appdata%\Local\Programs\Python\Python37

**Comment by ahahahaah** [comment]
yeah i have found it here C:\Users\ok\AppData\Local\Programs\Python\Python37\Scripts
what should i do with this folder?

**Comment by Xyrio** [comment]
i guess you should get the 32bit version otherwise you will end up having same problems as me ( #56 )

**Comment by lukasmonk** [comment]
I leave a link valid only for today:
https://www.filemail.com/d/agwvjqambbyorgh
Unzip,
then exec : WinPython Command Prompt.exe  from the folder created, a command prompt appear, then exec LucasR.bat

I have downloaded Winpython with 3.7.7 version of python
Then I have downloaded the LucasChessR2 sources from GitHub, then I have copied it as a subfolder of winpython
I have executing WinPython Command Prompt.exe, I have gone to Lucaschessr2, then pip install -r requirements.txt

**Comment by Xyrio** [comment]
i downloaded official: https://www.python.org/downloads/release/python-379/
lets see how far i get

**Comment by Xyrio** [comment]
i runs for me with official. now testing other one

**Comment by ahahahaah** [comment]
i dont know if i had done things correctly
ive unzipped the file and run the winpython command prompt.exe and directly typed lucasr.bat
![image](https://user-images.githubusercontent.com/69671446/210008394-b9b526a0-f6ce-4764-b6b7-1bbf34c7561a.png)

**Comment by Xyrio** [comment]
try uninstall the previously installed python 64 bit if it is still there?
then start the winpython prompt new and try again.

**Comment by Xyrio** [comment]
also see if `set PYTHONHOME` is empty or not.

**Comment by Xyrio** [comment]
well if it exists you need to remove it from the environment variables: 
hotkey: winkey + pause -> advanced system settings -> advanced (3rd tab) -> environment variables
http://4.bp.blogspot.com/-y8FlnjFFJmU/UGm-5SbUA9I/AAAAAAAAAtY/2snYlNXBuzY/s1600/advanced+system+settings+environment+variables+windows+7.PNG
in the next window find it in one of the 2 lists then delete it and pres ok on both windows

**Comment by ahahahaah** [comment]
1st ive uninstalled python, previously installed
same effect when i launch lucasr.py. the error message talks about "no module named 'encodings' " so maybe i have something not installed in my system?

2nd i don't understand what pythonhome is
i have typed "set py" in the winpython command prompt.exe 
here is the result 
![image](https://user-images.githubusercontent.com/69671446/210011597-98fca923-39f3-4d6d-8d87-5fd69a161641.png)

**Comment by Xyrio** [comment]
PYTHONHOME can cause the encodings problem. but you dont have it so hmm

**Comment by Xyrio** [comment]
check if PATH has any other python folders
`set PATH`

**Comment by Xyrio** [comment]
hmm try removing the PYTHON one. after you start the winpython console do:
`set PYTHON=`
that temporary removes it for the current window, then
`python -c "print('test')"`
to confirm that python works at all
then try lucasr.bat

**Comment by ahahahaah** [comment]
the test failed
![image](https://user-images.githubusercontent.com/69671446/210015064-dd951a11-263a-42ef-9534-5a04774e1d32.png)
wwwhen i lunch it i have the crash

**Comment by Xyrio** [comment]
unseting python failed: there is a = after set python like `set python=` .

**Comment by ahahahaah** [comment]
it's already a precious information, 
thanks

**Comment by Xyrio** [comment]
well one thing to try would be to to set the var:
`set PYTHONHOME=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\`
`python -c "print('test')"`

**Comment by Xyrio** [comment]
well check that you have the encoding folder with files:
```
WPy32-3771\python-3.7.7\Lib\encodings

aliases.py
ascii.py
base64_codec.py
big5.py
big5hkscs.py
bz2_codec.py
charmap.py
cp037.py
cp1006.py
cp1026.py
cp1125.py
cp1140.py
cp1250.py
cp1251.py
cp1252.py
cp1253.py
cp1254.py
cp1255.py
cp1256.py
cp1257.py
cp1258.py
cp273.py
cp424.py
cp437.py
cp500.py
cp65001.py
cp720.py
cp737.py
cp775.py
cp850.py
cp852.py
cp855.py
cp856.py
cp857.py
cp858.py
cp860.py
cp861.py
cp862.py
cp863.py
cp864.py
cp865.py
cp866.py
cp869.py
cp874.py
cp875.py
cp932.py
cp949.py
cp950.py
euc_jisx0213.py
euc_jis_2004.py
euc_jp.py
euc_kr.py
gb18030.py
gb2312.py
gbk.py
hex_codec.py
hp_roman8.py
hz.py
idna.py
iso2022_jp.py
iso2022_jp_1.py
iso2022_jp_2.py
iso2022_jp_2004.py
iso2022_jp_3.py
iso2022_jp_ext.py
iso2022_kr.py
iso8859_1.py
iso8859_10.py
iso8859_11.py
iso8859_13.py
iso8859_14.py
iso8859_15.py
iso8859_16.py
iso8859_2.py
iso8859_3.py
iso8859_4.py
iso8859_5.py
iso8859_6.py
iso8859_7.py
iso8859_8.py
iso8859_9.py
johab.py
koi8_r.py
koi8_t.py
koi8_u.py
kz1048.py
latin_1.py
mac_arabic.py
mac_centeuro.py
mac_croatian.py
mac_cyrillic.py
mac_farsi.py
mac_greek.py
mac_iceland.py
mac_latin2.py
mac_roman.py
mac_romanian.py
mac_turkish.py
mbcs.py
oem.py
palmos.py
ptcp154.py
punycode.py
quopri_codec.py
raw_unicode_escape.py
rot_13.py
shift_jis.py
shift_jisx0213.py
shift_jis_2004.py
tis_620.py
undefined.py
unicode_escape.py
unicode_internal.py
utf_16.py
utf_16_be.py
utf_16_le.py
utf_32.py
utf_32_be.py
utf_32_le.py
utf_7.py
utf_8.py
utf_8_sig.py
uu_codec.py
zlib_codec.py
__init__.py
__pycache__
__pycache__\aliases.cpython-37.pyc
__pycache__\cp1252.cpython-37.pyc
__pycache__\cp437.cpython-37.pyc
__pycache__\idna.cpython-37.pyc
__pycache__\latin_1.cpython-37.pyc
__pycache__\utf_16_be.cpython-37.pyc
__pycache__\utf_16_le.cpython-37.pyc
__pycache__\utf_8.cpython-37.pyc
__pycache__\__init__.cpython-37.pyc
```

**Comment by Xyrio** [comment]
since it cannot find stuff maybe telling it directly where to look helps:
```
set PYTHONHOME=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\
set PYTHONPATH=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\Lib
python -c "print('test')"
```

**Comment by ahahahaah** [comment]
hey with the pythonhome command  now the print test command works!! :D 
and now when i launch lucasr.py i don't have the same behaviour than previously
![image](https://user-images.githubusercontent.com/69671446/210057961-9542024f-7b3e-4971-8b94-f38ae1803ff4.png)

**Comment by ahahahaah** [comment]
OMGGGGGGGGG !!!!!!!!!!!!!!!!! i tryed what the error message said (to manually remove psutil etc...) and it worksssssssssss when i launch the lucasr.py !!!!!!!!!!!!!!!! :D :D :D :+1: 

but sadly when i launch the "normal" game (the lucasr.exe file version in the download section) it crashes like before :(
thank you i feel that the problem is about to be fixed !!

**Comment by ahahahaah** [comment]
doing all this to launch lucas R version each time is not convenient at all.
is there a way to fix the problem on my pc?
thanks

**Comment by Xyrio** [comment]
add the necessary lines to the lucasr.bat file:
```
cd /D %~dp0
set PYTHONHOME=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\
set PYTHONPATH=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\Lib
cd ..\LucasChessR2\bin
python LucasR.py
```
you can then make a shortcut with windows to the bat file
(cd /D %~dp0 line is necessary to be able to run it with a shortcut from anywhere)

**Comment by ahahahaah** [comment]
thanks for this solution, 
every time a new version will be released i will have to ask a new program like this one to work only for me, it will be annoying for lukasmonk (and me lol) to provide this kind of solution.
my best prospect is to find what's wrong in my side.
when i saw the solution above i thought it would help to identify the problem, it gave me some hope.

**Comment by ahahahaah** [comment]
in fact if i change the lucasr.bat file to your new commands nothing happened
a dos window opens and closes immediately

**Comment by ahahahaah** [comment]
if i type them (without the "cd /D %~dp0" line) on the WinPython Command Prompt.exe program, one by one it works, the lucasR.py is launched
if it type "cd /D %~dp0" line in the winpython command prompt.exe program i have a message that says the directory is not findable
if i type them in the lucasr.bat (located in the scripts folder) a dow window opens and closes immediately

**Comment by Xyrio** [comment]
as i wrote you have to add them to the LucasR.bat not type them yourself.
`cd /D %~dp0` only works in bat.
after you add them to the bat once you will not have to do it again. just start the bat then

**Comment by ahahahaah** [comment]
yes it is exactly what i did, and when i do it, a dos window opens and closes immediately.

when i wrote you the "winpython command prompt exe" part, it was to show you that these commands work with the winpython command prompt exe but they don't work when i type them in the bat file.
it's for this reason i wrote "if i type them in the lucasr.bat (located in the scripts folder) a dow window opens and closes immediately".

**Comment by Xyrio** [comment]
copy lucasr.bat and name it lucasr_start.bat then replace everything in the new file:
lucasr_start.bat
```
set _pydir=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\
set path=%_pydir%Lib\site-packages\PyQt5;%_pydir%Lib\site-packages\PySide2;%_pydir%;%_pydir%DLLs;%_pydir%Scripts;%_pydir%..\t;%_pydir%..\t\mingw32\bin;%_pydir%..\t\R\bin\i386;%_pydir%..\t\Julia\bin;%_pydir%..\n;%path%
set PYTHONHOME=%_pydir%
set PYTHONPATH=%_pydir%Lib
cd /D %~dp0
cd ..\LucasChessR2\bin
python LucasR.py
```
now you should be able to run lucasr_start.bat directly without winpython command prompt

**Comment by ahahahaah** [comment]
big thank you, this works better indeed!!

i tryed immediately to update to the last released version, r205b. the download window pops up, then the installation progress bar finished but when i relaunch the program it is still the r205a version.
i guess it is because i don't use the "normal" program?

**Comment by Xyrio** [comment]
yes you have the sourcecode.
the source is prioritiezed i guess.
you would have to update the sourcecode located in the LucasChessR2 folder.
on the main page https://github.com/lukasmonk/lucasChessR2 click the code button and download the zip then rename the old LucasChessR2 folder and extract so it matches same path LucasChessR2\bin folder.

to test download the normal version. if it is still not fixed you can update the source code. problem with source code is that it is the very latest and might have more bugs.

**Comment by ahahahaah** [comment]
ok, i see what you mean 
thanks dude for all your help

**Comment by ahahahaah** [comment]
hello again ^^

in the .bat file there is `set _pydir=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\
set path=%_pydir%Lib\site-packages\PyQt5;%_pydir%Lib\site-packages\PySide2;%_pydir%;%_pydir%DLLs;%_pydir%Scripts;%_pydir%..\t;%_pydir%..\t\mingw32\bin;%_pydir%..\t\R\bin\i386;%_pydir%..\t\Julia\bin;%_pydir%..\n;%path%
set PYTHONHOME=%_pydir%
set PYTHONPATH=%_pydir%Lib
cd /D %~dp0
cd ..\LucasChessR\bin
python LucasR.pyc`

i would like to move the whole folder (that contains python and lucaschess program).
but the 1st line of this script is set _pydir=C:\Users\ok\Desktop\WPy32-3771\python-3.7.7\
so i have to change this line everytime i move the folder in a new location, with a relative path there would be nothing to change if i move the folder.
how to write this line with a relative path? i tryed  set _pydir=..\python-3.7.7\
but it doesnt work.

**Comment by ahahahaah** [comment]
and thanks again, it works!!
after some tests it seems that a too long folder name (15 characters) and therefore a path name too long that contains this wpy32-3771 folder, causes the application to crash
if i rename it with a 14 characters name or less or if i move it directly to the c:\ folder so that the number of characters for the whole path is not too long then all works correctly.

it's weird, but not too annoying. just wanted to report it.
anyway!! all works
thanks again!!

**Comment by Xyrio** [comment]
that is a windows limitation that is probably better kept as is for backward compatiblity with programs.
