### ISSUE TITLE
Some issues, questions and suggestions

### ISSUE THREAD

**Issue by HarshilPatel007** [lukasmonk/lucaschessR2#61]
Hi all,

First of all, many many thanks for this awesome piece of software. My hunt of best chess client/tool for the linux is ended here.

**Version** :  R2.04 Wayland
**OS** : Arch
### How to contribute a new theme?
- This is a club tournament inspired theme. I called it tournament.
- I saw **UserData** directory and found out that, theme file is encrypted in **themes.pkd** file. While, in **Resources** directory, the themes are in **.lktheme3** and they are also encrypted.
  ### Theme Preview
  ![image](https://user-images.githubusercontent.com/16424866/210164424-c4c29452-e522-41ae-a075-a025044df7d6.png)

## Issues
- while working with this settings, I found some issues/bugs.
   - The window is not fully shown. (see the bottom, it is hidden and there is no way we can resize the window. DPI problem?) 
      
     ![image](https://user-images.githubusercontent.com/16424866/210164605-74ac1536-f7f3-4db2-a262-142dee4cf7d1.png)

## Suggestions
This are the UX, DX suggestions
- Change project slug/name to **lucaschess** . Why? The reason is the current name suggest the explicit version in it **(R2).**
Instead of specifying the version in project name, it is advisable to specify the version name in release binaries.
- Change the project structure to a standard.
   - The current project structure is mess IMO.
   - I found the code in **bin** directory. Which is not expected. The **bin** directory is for binaries, not for code.
   - Split the code in **src** directory and used libraries to **lib** directory.
- Remove some **ALPHA/BETA, OLD** engines.
  -  I saw some of the engines are in their early development phase and some of are not being maintained/has no activities since years. So, it is advisable to remove it from bundle and create a way for users to **plug-n-play**. So, if they wish, they can use them. This'll remove the clutter, reduce the bundle/binary size and headache of maintaining that engines.
- Update the **requirements**.
  - I saw, many requirements are out-of-date. Such as **python-chess** etc.
- Add highlight of **from-to-move**/**last-move** and **possible moves** just like, lichess or chess[.]com
  ![image](https://user-images.githubusercontent.com/16424866/210166343-6d4a6a9b-421b-478d-b260-3b7d1fe74ef2.png)

- Allow users to draw **possible-moves** arrows just like, lichess[.]com, chess[.]com or chessbase.
  ![image](https://user-images.githubusercontent.com/16424866/210166331-e23dcdee-0e3b-453e-85a0-a501875a6484.png)

**Comment by lukasmonk** [comment]
Thank you very much for your suggestions.

> ## Questions
> ### How to contribute a new theme?
> 
>     * This is a club tournament inspired theme. I called it tournament.
> 
>     * I saw **UserData** directory and found out that, theme file is encrypted in **themes.pkd** file. While, in **Resources** directory, the themes are in **.lktheme3** and they are also encrypted.

They are saved with a standard library, pickle.
themes.pkd and <any name>.lktheme3 have the same structure, so theme.pkd must be renamed to be popularised in Resources/Themes.

>       ### Theme Preview
>       ![image](https://user-images.githubusercontent.com/16424866/210164424-c4c29452-e522-41ae-a075-a025044df7d6.png)
> 
> 
> ## Issues
> 
>     * while working with this settings, I found some issues/bugs.
>       
>       * The window is not fully shown. (see the bottom, it is hidden and there is no way we can resize the window. DPI problem?)
>         ![image](https://user-images.githubusercontent.com/16424866/210164605-74ac1536-f7f3-4db2-a262-142dee4cf7d1.png)

**I have to work on it**. In windows there is no problem, maybe removing windows inheritance will be enough.

> 
> 
> ## Suggestions
> 
> This are the UX, DX suggestions
> 
>     * Change project slug/name to **lucaschess** . Why? The reason is the current name suggest the explicit version in it **(R2).**

>       Instead of specifying the version in project name, it is advisable to specify the version name in release binaries.

Perhaps in LucasChess 3


> 
>     * Change the project structure to a standard.
>       
>       * The current project structure is mess IMO.
>       * I found the code in **bin** directory. Which is not expected. The **bin** directory is for binaries, not for code.
>       * Split the code in **src** directory and used libraries to **lib** directory.

It mimics the distribution, I don't really like the rules in my work :). At the moment, I don't want any help on programming, so it's not a big problem.


> 
>     * Remove some **ALPHA/BETA, OLD** engines.

Not so easy and I like old engines.

>       
>       * I saw some of the engines are in their early development phase and some of are not being maintained/has no activities since years. So, it is advisable to remove it from bundle and create a way for users to **plug-n-play**. So, if they wish, they can use them. This'll remove the clutter, reduce the bundle/binary size and headache of maintaining that engines.


> 
>     * Update the **requirements**.
>       
>       * I saw, many requirements are out-of-date. Such as **python-chess** etc.

> 
>     * Add highlight of **from-to-move**/**last-move** and **possible moves** just like, lichess or chess[.]com
>       ![image](https://user-images.githubusercontent.com/16424866/210166343-6d4a6a9b-421b-478d-b260-3b7d1fe74ef2.png)

Perhaps in future
> 
>     * Allow users to draw **possible-moves** arrows just like, lichess[.]com, chess[.]com or chessbase.
>       ![image](https://user-images.githubusercontent.com/16424866/210166331-e23dcdee-0e3b-453e-85a0-a501875a6484.png)

Right button when activated in Options/Configuration/Board
F1/F10 to enter in directory mode.

**Comment by HarshilPatel007** [comment]
> It mimics the distribution, I don't really like the rules in my work :).

Actually, this'll make it harder to get the contribution.

> At the moment, I don't want any help on programming, so it's not a big problem.

Your wish. But, IMO, not a good thinking or approach to maintain a FOSS project. This'll make a barrier for potential contributions.

**Comment by lukasmonk** [comment]
> Allow users to change characteristics of arrow just like, how they do in theme building.

F1/F10, Director mode, and the arrows are editable.

**Comment by HarshilPatel007** [comment]
> F1/F10, Director mode, and the arrows are editable.

OMG, I this is insane.

Found another bug.
- F10 > Edit.
- The white thing dosn't go away. even we switch to another program/window.
![image](https://user-images.githubusercontent.com/16424866/211139845-8f34f066-9000-42d8-8541-e2d021ed8465.png)

![image](https://user-images.githubusercontent.com/16424866/211139967-4194ed1e-e483-45fe-b1e6-10bd3dfed677.png)

**Comment by lukasmonk** [comment]
F10 is not a good example, it is better to indicate F1-F9. 
F10 is used to launch a window to write comments in this context. 
Click the Remove option on the Director's toolbar to remove it.

**Comment by HarshilPatel007** [comment]
> Click the Remove option on the Director's toolbar to remove it.

Yes, it closed that. But, the real bug is when you keep open it and switch to another window/program, it appears on it as shown in above image. which is bug.

**Comment by lukasmonk** [comment]
Fixed.
