### ISSUE TITLE
docker run - crashes with "ImportError: libpulse-mainloop-glib.so.0: cannot open shared object file"

### ISSUE THREAD

**Issue by purplejacket** [lukasmonk/lucaschessR2#62]
I'm on MacOS.  I cloned the repo, built successfully using `docker build . -t lucaschess` then tried to start it, but got an error.

MacOS:
uname -a
Darwin mymachine 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

Here's the build and start:

docker build . -t lucaschess && docker run -it -e "DISPLAY=$DISPLAY" -v "$HOME/.Xauthority:/lucaschess/.Xauthority:ro" -v "$PWD/UserData:/lucaschess/UserData" --network host --rm lucaschess
[+] Building 117.8s (15/15) FINISHED                                                                                                 
 => [internal] load build definition from Dockerfile                                                                            0.0s
 => => transferring dockerfile: 762B                                                                                            0.0s
 => [internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 105B                                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.9-bullseye                                                          1.6s
 => [ 1/10] FROM docker.io/library/python:3.9-bullseye@sha256:b8ddeb68904299c09a39aff59d4a713862253b137fdd7ace3a3b7ba0391971b  28.4s
 => => resolve docker.io/library/python:3.9-bullseye@sha256:b8ddeb68904299c09a39aff59d4a713862253b137fdd7ace3a3b7ba0391971b1    0.0s
 => => sha256:68cf04410baf37bea3c13ed66e79302ea69aa5cdd7b436903f3932016b7356a1 8.51kB / 8.51kB                                  0.0s
 => => sha256:32de3c850997ce03b6ff4ae8fb00b34b9d7d7f9a35bfcdb8538e22cc7b77c29d 55.03MB / 55.03MB                                3.1s
 => => sha256:c796299bbbddc7aeada9539a4e7874a75fa2b6ff421f8d5ad40f227b40ab4d86 10.88MB / 10.88MB                                0.9s
 => => sha256:b8ddeb68904299c09a39aff59d4a713862253b137fdd7ace3a3b7ba0391971b1 1.86kB / 1.86kB                                  0.0s
 => => sha256:1f1b3b271a5839cf9437ef077d74b795c3f92dc700bf4d430752d652d75b13e9 2.22kB / 2.22kB                                  0.0s
 => => sha256:fa1d4c8d85a4e064e50cea74d4aa848dc5fc275aef223fcc1f21fbdb1b5dd182 5.16MB / 5.16MB                                  0.6s
 => => sha256:81283a9569ad5e90773f038daedd0d565810ca5935eec8f53b8bcb6a199030d6 54.58MB / 54.58MB                                3.7s
 => => sha256:60b38700e7fb2cdfac79b15e4c1691a80fe6b4101c7b7fea66b9e7cd64d961cf 196.88MB / 196.88MB                              8.7s
 => => sha256:0f67f32c26d393a2580062f2cebfde80cc4c5a5e264bbb7a32569c6c7551c1c2 6.29MB / 6.29MB                                  3.8s
 => => extracting sha256:32de3c850997ce03b6ff4ae8fb00b34b9d7d7f9a35bfcdb8538e22cc7b77c29d                                       5.5s
 => => sha256:f938eb1c6191bd4d7856656595586f62e984f504870c750f2821aa3c2a7fc93a 235B / 235B                                      3.9s
 => => sha256:4571fc720a5141c1fac0427e1b9d593f60e0e6a8c646293d56d81d1fee84b3f6 18.32MB / 18.32MB                                4.9s
 => => sha256:61498f7c3a6335b61bcd04e95f26b116ca729b5f93ce751150f5eca6b632de83 2.88MB / 2.88MB                                  4.3s
 => => extracting sha256:fa1d4c8d85a4e064e50cea74d4aa848dc5fc275aef223fcc1f21fbdb1b5dd182                                       0.5s
 => => extracting sha256:c796299bbbddc7aeada9539a4e7874a75fa2b6ff421f8d5ad40f227b40ab4d86                                       0.7s
 => => extracting sha256:81283a9569ad5e90773f038daedd0d565810ca5935eec8f53b8bcb6a199030d6                                       5.1s
 => => extracting sha256:60b38700e7fb2cdfac79b15e4c1691a80fe6b4101c7b7fea66b9e7cd64d961cf                                      10.3s
 => => extracting sha256:0f67f32c26d393a2580062f2cebfde80cc4c5a5e264bbb7a32569c6c7551c1c2                                       0.3s
 => => extracting sha256:4571fc720a5141c1fac0427e1b9d593f60e0e6a8c646293d56d81d1fee84b3f6                                       0.6s
 => => extracting sha256:f938eb1c6191bd4d7856656595586f62e984f504870c750f2821aa3c2a7fc93a                                       0.0s
 => => extracting sha256:61498f7c3a6335b61bcd04e95f26b116ca729b5f93ce751150f5eca6b632de83                                       0.3s
 => [internal] load build context                                                                                              23.2s
 => => transferring context: 877.35MB                                                                                          23.2s
 => [ 2/10] WORKDIR /lucaschess/                                                                                                0.9s
 => [ 3/10] RUN apt-get update &&  apt-get install -y portaudio19-dev libqt5gui5 &&  rm -rf /var/lib/apt/lists/*               31.1s
 => [ 4/10] ADD requirements.txt ./                                                                                             0.0s
 => [ 5/10] RUN pip install -r requirements.txt                                                                                26.3s
 => [ 6/10] ADD . .                                                                                                             2.3s 
 => [ 7/10] RUN cd bin/_fastercode && chmod a+x ./linux64.sh && ./linux64.sh                                                   21.4s 
 => [ 8/10] RUN cd bin/_genicons && python ./gentema.py                                                                         0.4s 
 => [ 9/10] RUN chmod a+x bin/LucasR.py                                                                                         0.4s 
 => [10/10] WORKDIR /lucaschess/bin/                                                                                            0.0s 
 => exporting to image                                                                                                          4.9s 
 => => exporting layers                                                                                                         4.9s 
 => => writing image sha256:130905e2b3a1a08b778c48c65d7269d97439061fa91ceed1fdbb2353465032b3                                    0.0s
 => => naming to docker.io/library/lucaschess                                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Traceback (most recent call last):
  File "/lucaschess/bin/./LucasR.py", line 17, in <module>
    import Code.Base.Init
  File "/lucaschess/bin/Code/Base/Init.py", line 5, in <module>
    from Code import Procesador
  File "/lucaschess/bin/Code/Procesador.py", line 77, in <module>
    from Code.Sound import WindowSonido
  File "/usr/local/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/lucaschess/bin/Code/Sound/WindowSonido.py", line 20, in <module>
    from Code.Sound import Sound
  File "/usr/local/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/lucaschess/bin/Code/Sound/Sound.py", line 8, in <module>
    from PySide2 import QtCore, QtMultimedia
  File "/usr/local/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory

**Comment by lukasmonk** [comment]
Sorry, I have no idea.
