### ISSUE TITLE
Unable to access to games stored in Database on linux

### ISSUE THREAD

**Issue by pachorrus** [lukasmonk/lucaschessR2#64]
Hi,

Just downloaded lucasR2.05b. I installed but it would not start. I had to uninstall everything (copying UserData directory in another place). Then i installed again LucasChessR, i deleted UserData and copied my UserData. 

But now, i am not able to access my games. When i click on Herramientas/Bases de Datos/Mis Partidas, nothing happens. Maybe when i removed the UserData from LucasR in order to copy mine i deleted something important? In that case, i could uninstall, reinstall and how i could copy all my UserData? By hand?

**Comment by lukasmonk** [comment]
There are a file = bug.log in the bin folder of the program, perhaps it has the information, please show it or send it to me.

**Comment by pachorrus** [comment]
For sake of clearness, I started the app, and the only thing i did was to try to open Mis Partidas database. This is the log

[bug.log](https://github.com/lukasmonk/lucaschessR2/files/10414899/bug.log)

**Comment by lukasmonk** [comment]
Please, remove file QTUtil.pyc and copy this file:
[bin/Code/QTUtil](https://github.com/lukasmonk/lucaschessR2/blob/main/bin/Code/QT/QTUtil.py)

**Comment by pachorrus** [comment]
It is working now. Thanks!!!!!!

Shall i close this issue?

**Comment by lukasmonk** [comment]
You can close it, as I have already released the update.

**Comment by pachorrus** [comment]
Thanks to you, really. :-)
