### ISSUE TITLE
Maybe lucaschess need to optimized for GPU engine analysis like LC0

### ISSUE THREAD

**Issue by shenjian333333** [lukasmonk/lucaschessR2#66]
Use depth to control GPU engine analyze sometimes is too slow,In some positions, LC0 can take 5 minutes or more to complete an 8 depths analysis,Maybe we can use nodes control analysis,for example ，10000nodes 1 PV,this analysis must be reliable. And kitibizers function can be turned into an analysis arrow orchange that window to can maximized.That's my suggestion，My English is not good, part of the text uses Google Translate, please forgive me. 😁😁  
Happy new year!

**Comment by lukasmonk** [comment]
In the analysis, if depth and fixed time are given, then the target is the depth with the time limit.
Nodes are too specific.

**Comment by shenjian333333** [comment]
Thanks for your reply
  But for gpu engines depths are doesn't make sense ,if I limit time ,Idon`t konw how many nodes did it ran,and I can`t know are the results reliable.

**Comment by texium** [comment]
lc0 depth is not the same as other engines, it searches and makes a tree by using Monte Carlo graph search. depth is just an estimation but not really how far it is searched

**Comment by texium** [comment]
this should probably be closed, there's not really a way to optimize other than adding an option for nodes per move

**Comment by shenjian333333** [comment]
> this should probably be closed, there's not really a way to optimize other than adding an option for nodes per move

So, should I close this issue or just keep it?

**Comment by lukasmonk** [comment]
Better to keep it, as it reminds me that this possibility is pending.

**Comment by texium** [comment]
> Better to keep it, as it reminds me that this possibility is pending, and it could be useful to someone.

nodes per move is an option I've wanted for a while. as you might know, arena has it, but their app is clunky, and cutechess has it but they're kinda annoying. you might also want to look at arena's features and find some implementations. It has the elostat thing built in
