### ISSUE TITLE
Unable to train with "Juega como un gran maestro" (LINUX)

### ISSUE THREAD

**Issue by pachorrus** [lukasmonk/lucaschessR2#67]
When i click on "Juega como un gran maestro", nothing happens. Looking into the bug.log, the last line is: 

FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/home/javi/LucasChessR/Resources/GM/_ListaGM.txt'

Looking into the folder, the file is called _listaGM.txt. As Linux is case sensitive (i guess this problem does not appear on windows), the file is not found. So either the name of the file should be changed to _ListaGM.txt, or in line 217 of GM.py the name should change to _listaGM.txt

For me is not a critical issue (i changed the name of file and it is working).

Thanks for this wonderful app!!

**Comment by lukasmonk** [comment]
I have published a new update that fix this problem.
Muchas gracias.

**Comment by pachorrus** [comment]
Muchas gracias a ti por todo!
