### ISSUE TITLE
Unable to set a game with rodent II personalities (LINUX)

### ISSUE THREAD

**Issue by pachorrus** [lukasmonk/lucaschessR2#69]
I click on "Jugar", and when i try to choose "Oponente", "Rodent II personalidades" do not show the personalities, so i cannot choose anyone. No bug.log entries either.

However, as i have a league (i created it a few months ago with LucasChess version 2.04) with several rodent II personalities, when i play the league, the rodent II personalities can play. I mean, it seems that the rodent II personalities are there, but LucasChess (on Linux) cannot access them to be chosen.

Just curious, i created another league with version 2.05c, and when i add engines, the rodent II personalities are not in the list.

Thanks in advance.

**Comment by pachorrus** [comment]
I have been taking a look at the code, and I saw that in file SelectEngines.py you changed, in line 82, from "rodentii" to "rodentII". Linux is case sensitive, so now luchasChess cannot find personalities.ini (in fact, it is looking on rocinante directory).

However, changing again to "rodentii" still does not work (it gets stuck with the message "Leyendo personalidades"). That is because now, in SelectEngines.get_engines_rodent function, the code looks for three parameters separated by "|" (text, author and elo), while in personalities.ini there are only two parameters separated by "|". (In fact, in most of the personalities there is no elo). If the personalities.ini is modified to have three parameters separated by "|", it works (i tried only putting two personalities with three parameter each, just for testing).

I you want, i can try to modify the whole personalities.ini to be adapted to your code (except for line 82 "rodentii", that is something you have to change), but i am not sure which elos are accurate for each personality.



What i cannot understand is, in previous version, when i created a league with several rodentii personalities, lucasChess put different elos to several personalities (specially from the school directory), quite accurately, but i do not know from where lucasChess got these elos.

**Comment by lukasmonk** [comment]
Fixed, rodentII convert to rodentii internally.

**Comment by lukasmonk** [comment]
Thank you very much, I´ll try to publish, today or tomorrow.

**Comment by pachorrus** [comment]
[personalities.ini.txt](https://github.com/lukasmonk/lucaschessR2/files/10474517/personalities.ini.txt)

i have attached the personalities.ini with three expected parameters, in case you want to change it. (remove the extension .txt, as github wouldn't allow to attach a .ini file)

**Comment by lukasmonk** [comment]
Thanks. I have copied that in win32.
