### ISSUE TITLE
Adding ability to add variations in the window of individual moves in "Moves tree" 

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR2#7]
Hi,
After analysis of engine in "Moves tree" you get various moves ranked as per their score. After double clicking any one of them, you see a window showing entire variation of that move. It would be very useful to include variations manually in this window.

**Comment by lukasmonk** [comment]
Variations in this window are displayed by pressing +.

**Comment by futurelauncher** [comment]
I am NOT referring this window. 
![image](https://user-images.githubusercontent.com/60097814/187488237-6e436934-f77c-4192-8872-eb2fa4f2a5a0.png)
I am referring this window. The one at front.
![image](https://user-images.githubusercontent.com/60097814/187488590-ef706028-35df-4b11-a725-943059f302cf.png)

**Comment by futurelauncher** [comment]
The problem with the approach of navigating the moves in your diagram is that, here you cannot go through a variation line easily  (navigating with the help of keyboard).
