### ISSUE TITLE
finishing a season on a league, the league stop working (LINUX)

### ISSUE THREAD

**Issue by pachorrus** [lukasmonk/lucaschessR2#70]
Hi,

I have just finished a season on a league and the panel with the league information did not show up. Trying to open the league again, it does not work. I attach the bug.log.
[bug.log](https://github.com/lukasmonk/lucaschessR2/files/10456174/bug.log)

**Comment by pachorrus** [comment]
Just in case, it think it could be relevant that these league was created with a previous version of LucasChess (2.04 or 2.03, i do not recall)

**Comment by pachorrus** [comment]
I've got the problem. In line 639:  li_panels = season_previous.gen_panels_classification()

but get_panels_classification() return 2 variables and the second one was is different. But li_panel is adding this variable also, as it is different, it got an error.

Replacing line 639 with:

 li_panels, kk = season_previous.gen_panels_classification()

it works!!! (kk is the name of the second variable that is returned, but not used).

**Comment by lukasmonk** [comment]
Yes, this is the problem, fixed.

**Comment by lukasmonk** [comment]
I´ll try to publish, today or tomorrow.
