### ISSUE TITLE
Competition with tutor

### ISSUE THREAD

**Issue by TheLegalist** [lukasmonk/lucaschessR2#72]
When I play with "competition with tutor", if I try to play with a level/depth that I already played with (ex. I already defeated the engine at Beginner 1, but am playing it with Beginner 1 again), even though I'm not supposed to get points for it, the screen shows that I beat the next depth (ex. Beginner Level 1 +White:2) even though I played at level 1 again.

**Comment by lukasmonk** [comment]
Fixed.
A very very old bug.
Bien visto!
Thank you very much
