### ISSUE TITLE
In 2.05d,Lucas chess can`t use Berserk11.1

### ISSUE THREAD

**Issue by shenjian333333** [lukasmonk/lucaschessR2#75]
Berserk11.1 abnormal exit while analyzing,but Berserk10 can normal exec.， GUI cant save enginelog because it happens in seconds，maybe its a new bug.

**Comment by shenjian333333** [comment]
> I cannot reproduce the problem. It works on my PC without any crashes. (avx512 does not work on my PC, the rest yes) What are the parameters you indicate when analysing? Which version of Bersek do you use, avx2, pext, ...? Does that version run directly on your PC?.

I used avx2 PEXT but cant use that.

**Comment by lukasmonk** [comment]
There are two versions pext, berserk-11-x64-avx512-pext.exe, berserk-11-x64-avx2-pext.exe
I can´t use in my PC (then also in Lucas Chess) berserk-11-x64-avx512-pext.exe
But the test you could do is to run the version that doesn't work properly in Lucas Chess, outside Lucas Chess, with windows explorer, double click on it.

**Comment by shenjian333333** [comment]
![image](https://user-images.githubusercontent.com/93416267/220584329-94044001-e3c4-4d4f-b989-42bdcfa3283b.png)
![image](https://user-images.githubusercontent.com/93416267/220584492-f42f49a8-8d29-4cd2-abc5-c7baa6350149.png)

**Comment by shenjian333333** [comment]
New situation，berserk11.1 cannot run on cutechess too 
Thats so strange 
![image](https://user-images.githubusercontent.com/93416267/220586835-4d51046f-4b9e-4376-b6bf-c70e87dacafc.png)
It was just run 11s

**Comment by lukasmonk** [comment]
Also using basic version? (I have no idea but perhaps pext is the problem)

**Comment by shenjian333333** [comment]
![image](https://user-images.githubusercontent.com/93416267/220587550-7e0084cc-eaec-40d1-bcbb-106c7df95da7.png)

**Comment by shenjian333333** [comment]
> 还用基础版？（我不知道，但也许 pext 是问题所在）

But I use i7CPU
设备名称	DESKTOP-E38LAKK
处理器	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
设备 ID	08F94444-5CA0-4BE4-894F-C37821C3A188
产品 ID	00342-35906-43644-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	笔支持

**Comment by lukasmonk** [comment]
The hardware you use does not seem to be the problem.

**Comment by shenjian333333** [comment]
Maybe I shoud ask berserk`s author

**Comment by shenjian333333** [comment]
Berserk`s author can`t fix it too,so maybe It`s my computer`s problem,I just close the issue and wait next win10 update.
