### ISSUE TITLE
Remove duplicate games from a database

### ISSUE THREAD

**Issue by maximmasiutin** [lukasmonk/lucaschessR2#76]
I have imported several games from PGN files, but some games are imported twice or more times. 

Please consider a feature (a toolbar button "Deduplicate" or "Utilities" -> Deduplicate) to remove duplicate games, i.e. entries which have all attributes equal.

Or should I implement this option and create a pull request?

**Comment by lukasmonk** [comment]
Done

**Comment by maximmasiutin** [comment]
Thank you very much for the prompt action! That feature works great, I have used it in the latest version that you released!
