### ISSUE TITLE
Elo Limitation problem With Rodent_IV 

### ISSUE THREAD

**Issue by upsetfox** [lukasmonk/lucaschessR2#77]
I'm using Rodent_IV with its personalities like "Amanda".the problem is even though I set it elo to 800 only it can beat gm Carlsen. 
i set hash, and depth same for both but it can beat gm carlsen and others in engine matches in no time . even though I set its elo to 800  its elo is way better than 800. this issue also has with lucas 2.6 edition

**Comment by lukasmonk** [comment]
You should test the engine logs to find out what the problem is, and determine whether it is a Lucas Chess problem or engine misconfiguration, or an engine problem.

**Comment by upsetfox** [comment]
i Should have done more research before posting the issue. I find out this is not lukas issue. it is Rodent engine.
here is GitHub about the issue. [](https://github.com/nescitus/rodent-iv/issues/7).
