### ISSUE TITLE
Bug of "Moves tree"

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR2#9]
To replicate -
1) Open Moves tree for any move
2) Click Analyze and Accept
3) Once analysis is over, double click any analysed move in Score column
4) A window will open showing entire engine suggested variation
5) In this window, double click any move to analyse it
6) After some time analysis will complete and add multiple move possibilities to this move
7) Click Accept button on top left corner
8) Re-open this same window by double clicking on same move in Score column
9) Here is the bug, all alternative moves previously analysed by engine are vanished

**Comment by lukasmonk** [comment]
Only the movements shown on that screen are saved, without including variations, comments and so on.
Other operations are allowed, such as additional analysis, but only for consultation.
The system of saving the information does not allow it, maybe I should think of another system to save all this information.
